### ISSUE TITLE
berks install still failing

### ISSUE THREAD

**Issue by juliandunn** [berkshelf/berkshelf#1125]
I had a similar problem to the poster in #1116 but I'm pretty sure it's not a PEBKAC, so I'm reopening another issue. I'm running master as of today and Berkshelf is failing to solve a simple case:

```
$ berks install
Resolving cookbook dependencies...
Fetching 'annotate' from source at ../annotate
Fetching 'app_cm' from source at .
Fetching cookbook index from https://api.berkshelf.com/...
Unable to find a solution for demands: annotate (1.0.0), app_cm (0.1.0)
```

where the Berksfile is:

```
source 'https://api.berkshelf.com/'

cookbook 'annotate', path: '../annotate'
metadata
```

and a sanitized version of `berks install -d` (with paths obfuscated) is:

```
I, [2014-04-11T22:35:59.360960 #30785]  INFO -- : Reducing lockfile
D, [2014-04-11T22:35:59.361017 #30785] DEBUG -- : Current lockfile:
D, [2014-04-11T22:35:59.361040 #30785] DEBUG -- :
D, [2014-04-11T22:35:59.361069 #30785] DEBUG -- :   DEPENDENCIES
D, [2014-04-11T22:35:59.361090 #30785] DEBUG -- :
D, [2014-04-11T22:35:59.361118 #30785] DEBUG -- :   GRAPH
D, [2014-04-11T22:35:59.361139 #30785] DEBUG -- :
D, [2014-04-11T22:35:59.361167 #30785] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2014-04-11T22:35:59.361186 #30785] DEBUG -- : Removing transitive dependencies
D, [2014-04-11T22:35:59.361228 #30785] DEBUG -- :   Checking annotate (>= 0.0.0)
D, [2014-04-11T22:35:59.361253 #30785] DEBUG -- :     Skipping (not graphed)
D, [2014-04-11T22:35:59.361276 #30785] DEBUG -- :   Checking app_cm (>= 0.0.0)
D, [2014-04-11T22:35:59.361305 #30785] DEBUG -- :     Skipping (not graphed)
D, [2014-04-11T22:35:59.361334 #30785] DEBUG -- : New lockfile:
D, [2014-04-11T22:35:59.361353 #30785] DEBUG -- :
D, [2014-04-11T22:35:59.361394 #30785] DEBUG -- :   DEPENDENCIES
D, [2014-04-11T22:35:59.361416 #30785] DEBUG -- :
D, [2014-04-11T22:35:59.361435 #30785] DEBUG -- :   GRAPH
D, [2014-04-11T22:35:59.361463 #30785] DEBUG -- :
Resolving cookbook dependencies...
I, [2014-04-11T22:35:59.361514 #30785]  INFO -- : Checking if lockfile is trusted
D, [2014-04-11T22:35:59.361543 #30785] DEBUG -- : Checking annotate (>= 0.0.0)
D, [2014-04-11T22:35:59.361565 #30785] DEBUG -- :   Not in lockfile - cannot be trusted!
I, [2014-04-11T22:35:59.361585 #30785]  INFO -- : Installing from universe
Fetching 'annotate' from source at ../annotate
D, [2014-04-11T22:35:59.362766 #30785] DEBUG -- : Using 'chefignore' at '/Users/juliandunn/Documents/Clients/Customer_Name_Elided/customer_name_elided/cookbooks/annotate/chefignore'
Fetching 'app_cm' from source at .
D, [2014-04-11T22:35:59.369140 #30785] DEBUG -- : Using 'chefignore' at '/Users/juliandunn/Documents/Clients/Customer_Name_Elided/customer_name_elided/cookbooks/app_cm/chefignore'
D, [2014-04-11T22:35:59.383440 #30785] DEBUG -- :   Creating a resolver
Fetching cookbook index from https://api.berkshelf.com/...
D, [2014-04-11T22:36:03.493201 #30785] DEBUG -- : ==> parsing Chef response body as JSON
D, [2014-04-11T22:36:04.382148 #30785] DEBUG -- : Using 'chefignore' at '/Users/juliandunn/Documents/Clients/Customer_Name_Elided/customer_name_elided/cookbooks/annotate/chefignore'
D, [2014-04-11T22:36:04.389706 #30785] DEBUG -- :   Adding explicit dependency on annotate (1.0.0) '/Users/juliandunn/Documents/Clients/Customer_Name_Elided/customer_name_elided/cookbooks/annotate'
D, [2014-04-11T22:36:04.390898 #30785] DEBUG -- : Using 'chefignore' at '/Users/juliandunn/Documents/Clients/Customer_Name_Elided/customer_name_elided/cookbooks/app_cm/chefignore'
D, [2014-04-11T22:36:04.395651 #30785] DEBUG -- :   Adding explicit dependency on app_cm (0.1.0) '/Users/juliandunn/Documents/Clients/Customer_Name_Elided/customer_name_elided/cookbooks/app_cm'
D, [2014-04-11T22:36:04.395758 #30785] DEBUG -- :   Starting resolution...
Unable to find a solution for demands: annotate (1.0.0), app_cm (0.1.0)
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/resolver.rb:83:in `rescue in resolve'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/resolver.rb:73:in `resolve'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/installer.rb:158:in `install_from_universe'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/installer.rb:39:in `run'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/berksfile.rb:371:in `install'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/cli.rb:143:in `install'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/cli.rb:52:in `dispatch'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/lib/berkshelf/cli.rb:27:in `execute!'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.0.rc1/bin/berks:5:in `<top (required)>'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/bin/berks:23:in `load'
    /Users/juliandunn/.rbenv/versions/1.9.3-p484/bin/berks:23:in `<main>'
```

metadata.rb contains:

```
name             'app_cm'
maintainer       'Chef Software, Inc.'
maintainer_email 'jdunn@getchef.com'
license          'Apache 2.0'
description      'Installs and configures [customer-appname-elided] components'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'annotate'
depends 'tomcat'
```

**Comment by spuder** [comment]
I'm encountering this problem today. Was the root cause ever identified? 

```
Fetching 'iis' from https://github.com/opscode-cookbooks/iis.git (at master)
Fetching 'windows' from https://github.com/opscode-cookbooks/windows.git (at master)
Fetching cookbook index from https://supermarket.chef.io...
Error retrieving universe from source: https://supermarket.chef.io
  * [Berkshelf::APIClient::ServiceUnavaiable] execution expired
```
