### ISSUE TITLE
PaxHeader directories when installing certain cookbooks

### ISSUE THREAD

**Issue by brenttheisen** [berkshelf/berkshelf#1132]
I'm installing a cookbook that appears to have been packaged with bsdtar using this Berksfile...

````ruby
source "https://api.berkshelf.com"

cookbook 'filesystem'
````

After performing a `berks vendor` there are several `PaxHeader` directories in the ensuing directory structure...

````
wasted:womply_kitchen brent$ berks vendor cookbooks
Resolving cookbook dependencies...
Using filesystem (0.8.2)
Using lvm (1.0.8)
Using xfs (1.1.0)
Vendoring filesystem (0.8.2) to /Users/brent/womply_kitchen/cookbooks/filesystem
Vendoring lvm (1.0.8) to /Users/brent/womply_kitchen/cookbooks/lvm
Vendoring xfs (1.1.0) to /Users/brent/womply_kitchen/cookbooks/xfs
wasted:womply_kitchen brent$ find cookbooks -name 'PaxHeader'
cookbooks/filesystem/attributes/PaxHeader
cookbooks/filesystem/libraries/PaxHeader
cookbooks/filesystem/PaxHeader
cookbooks/filesystem/providers/PaxHeader
cookbooks/filesystem/recipes/PaxHeader
cookbooks/filesystem/resources/PaxHeader
wasted:womply_kitchen brent$ ls -l cookbooks/filesystem/attributes/PaxHeader/*.rb
-rw-r--r-- 1 brent staff 140 Apr 15 15:56 cookbooks/filesystem/attributes/PaxHeader/default.rb
````

Generally these `PaxHeaders` aren't much of a problem and so I think most people don't notice. But in this case with the `filesystem` cookbook one of the `.rb` files inside a `PaxHeader` directory is being required which causes it to fail with a syntax error.

This issue has already been pretty well documented in a [Chef issue](https://tickets.opscode.com/browse/CHEF-4107?page=com.atlassian.jira.plugin.system.issuetabpanels:changehistory-tabpanel). However, I don't think that was the correct place to raise the issue as these `PaxHeader` directories are being created by the dependency Berkshelf has on minitar.

There are several ways to resolve this. Which way were you all planning on going with it?

**Comment by mrjcleaver** [comment]
I just encountered this during a berks upload of dependencies for elkstack:

````
Uploaded percona (0.15.5) to: 'https://myserver:443/'
E, [2015-01-19T13:41:58.103343 #4263] ERROR -- : Cookbook file attributes/PaxHeader/default.rb has a ruby syntax error:
E, [2015-01-19T13:41:58.103490 #4263] ERROR -- : /Volumes/Storage/martincleaver/.berkshelf/cookbooks/percona-multi-0.1.0/attributes/PaxHeader/default.rb:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
E, [2015-01-19T13:41:58.103523 #4263] ERROR -- : 18 gid=1604020879
E, [2015-01-19T13:41:58.103584 #4263] ERROR -- :       ^
E, [2015-01-19T13:41:58.105093 #4263] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid ruby files in cookbook: percona-multi (0.1.0).
E, [2015-01-19T13:41:58.105162 #4263] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook.rb:198:in `validate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/resources/cookbook_resource.rb:197:in `upload'
````

It took an indelicate find and rm to get rid of them.

**Comment by ernie58** [comment]
Any news on this?
