### ISSUE TITLE
Error disabling SSL

### ISSUE THREAD

**Issue by jp** [berkshelf/berkshelf#1144]
With the following configuration :

```
{
  "ssl": {
    "verify": false
  }
}
```

I can't upload my cookbooks with the `berks upload` command :

```
/home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:350:in `each': task was terminated (Celluloid::Task::TerminatedError)
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:350:in `cleanup'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:334:in `shutdown'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:326:in `handle_crash'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:161:in `rescue in run'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:147:in `run'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:129:in `block in start'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/internal_pool.rb:99:in `call'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/internal_pool.rb:99:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:92:in `value'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/uploader.rb:54:in `block (2 levels) in upload'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/uploader.rb:50:in `each'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/uploader.rb:50:in `block in upload'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/ridley-3.1.0/lib/ridley/client.rb:36:in `open'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/ridley-3.1.0/lib/ridley.rb:51:in `open'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf.rb:156:in `ridley_connection'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/uploader.rb:49:in `upload'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/uploader.rb:36:in `run'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/berksfile.rb:542:in `upload'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/cli.rb:208:in `upload'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/cli.rb:52:in `dispatch'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/lib/berkshelf/cli.rb:27:in `execute!'
        from /home/jpellet/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.1/bin/berks:5:in `<top (required)>'
        from /home/jpellet/.rbenv/versions/2.1.1/bin/berks:23:in `load'
        from /home/jpellet/.rbenv/versions/2.1.1/bin/berks:23:in `<main>'

```

**Comment by Bregor** [comment]
Hello, all.
The error still exists, but not for any cookbook (seems strange, yes).

Example:

	Uploaded crontab (0.0.1)
	Uploaded java (1.28.0)
	Uploaded mdadm (0.0.2)
	...
	/Users/bregor/.rvm/gems/ruby-2.2.0@emchef/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each': task was terminated (Celluloid::Task::TerminatedError)
	from /Users/bregor/.rvm/gems/ruby-2.2.0@emchef/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
	from /Users/bregor/.rvm/gems/ruby-2.2.0@emchef/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
	from /Users/bregor/.rvm/gems/ruby-2.2.0@emchef/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'

In my case error exists only for "python" cookbook:

    $ berks upload python
    /Users/bregor/.rvm/gems/ruby-2.2.0@emchef/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each': task was terminated (Celluloid::Task::TerminatedError)
	from /Users/bregor/.rvm/gems/ruby-2.2.0@emchef/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
	from /Users/bregor/.rvm/gems/ruby-2.2.0@emchef/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'

**Comment by Bregor** [comment]
P.S. seems to be ruby-2.2-related issue:
with ruby-2.1.5 upload done successfully.
