### ISSUE TITLE
installing gem dep-selector-libgecode takes forever

### ISSUE THREAD

**Issue by jedi4ever** [berkshelf/berkshelf#1166]
As part of the new berkshelf, the dep-selector-libgecode was introduced.
On a moderate macbook/build system this takes a long time, with no output.
I assume it's compiling. 

So it might be a very fast compiler , but it takes forever to install.
On build systems like circleci, it even hits the default timeout.

I know this only needs to be done once (ideally), but clean build environments are taking an awefull lot longer as in the previous version. I don't think the time of compile vs install is really in balance here. Maybe releasing a binary gem might speed up things.

**Comment by fletchowns** [comment]
@reset I installed via ChefDK but I'm still sitting here at "Installing dep-selector-libgecode 1.0.2 with native extensions" for about 5 minutes after a `chef exec bundle install`. Is that not supposed to be happening?

**Comment by fletchowns** [comment]
I tried the tar thing, didn't seem to help.
```
$ which tar
/usr/bin/tar
$ tar --version
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```
Then put chefdk bin on PATH:
```
$ export PATH=/c/opscode/chefdk/bin:$PATH
$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

Here's the last bit of the failure:
```
$ chef exec bundle install
...
...
...
make doinstalllib
make[1]: Entering directory `/c/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3'
mkdir -p C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib && \
        mkdir -p C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib && \
        mkdir -p C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/bin && \
        for_libtargets=" libgecodesupport.a libgecodekernel.a libgecodesearch.a libgecodeint.a libgecodeset.a libgecodeminimodel.a libgecodedriver.a   " && \
          for f in $for_libtargets; do \
            cp $f C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib; done && \
        for_liblinktargets="" && \
          for f in $for_liblinktargets; do \
            cp -pR $f C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib; done &&\
        for_liblibtargets="" && \
          for f in $for_liblibtargets; do \
            cp $f C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib; done &&\
        for_exetargets=" tools/flatzinc/mzn-gecode.bat" && \
          for f in $for_exetargets; do \
            cp $f C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/bin; done
mkdir: cannot create directory `C:/Users/Greg': Permission denied
mkdir: cannot create directory `Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib': File or path name too long
make[1]: *** [doinstalllib] Error 1
make[1]: Leaving directory `/c/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3'
make: *** [installlib] Error 2
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
        from extconf.rb:97:in `chdir'
        from extconf.rb:97:in `run'
        from extconf.rb:104:in `<main>'
-> sh C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3/configure --prefix=C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode --disable-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disable-doc-docset --disable-qt --disable-examples --disable-flatzinc --with-host-os=windows
-> make clean
-> make -j 5
-> make install

extconf failed, exit code 1

Gem files will remain installed in C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2 for inspection.
Results logged to C:/Users/Greg Barker/AppData/Local/chefdk/gem/ruby/2.1.0/extensions/x86-mingw32/2.1.0/dep-selector-libgecode-1.0.2/gem_make.out
Using thor 0.19.1
Using builder 3.2.2
Using coderay 1.1.0
Using excon 0.45.4
Using method_source 0.8.2
Using slop 3.6.0
Using net-ssh 3.0.2
Using little-plugger 1.1.4
Using multi_json 1.11.2
Using nori 2.6.0
Using rubyntlm 0.5.3
Using rubyzip 1.1.7
Using rainbow 2.1.0
Using mixlib-install 0.7.1
Using safe_yaml 1.0.4
Using bundler 1.12.4
Using aws-sdk-core 2.2.14
Using faraday 0.9.2
Using varia_model 0.4.1
Using buff-shell_out 0.2.0
Using timers 4.0.4
Using win32-process 0.8.3
Using gssapi 1.2.0
Using rspec-core 3.4.2
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.1
An error occurred while installing dep-selector-libgecode (1.0.2), and Bundler
cannot continue.
Make sure that `gem install dep-selector-libgecode -v '1.0.2'` succeeds before
bundling.
```

Emphasis these lines:
```
mkdir: cannot create directory `C:/Users/Greg': Permission denied
mkdir: cannot create directory `Barker/AppData/Local/chefdk/gem/ruby/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib': File or path name too long
```

I guess it can't handle the space in the path to my user folder?
