### ISSUE TITLE
`berks install` with bogus source location shouldn't crash berkshelf

### ISSUE THREAD

**Issue by dougireton** [berkshelf/berkshelf#1195]
## Repo steps:

Using berkshelf 3.1.2
Create a Berksfile with a bogus source URL:

``` ruby
source 'http://bogus.example.com'

metadata
```

``` bash
$ berks install
```
## Result

``` bash
Resolving cookbook dependencies...
Fetching 'my_cookbook' from source at .
Fetching cookbook index from http://bogus.example.com...
Error retrieving universe from source: http://bogus.example.com
  * [Berkshelf::APIClient::ServiceUnavaiable] service unavailable at: http://bogus.example.com
Using apt (2.3.10)
Using build-essential (2.0.2)
Using chef_handler (1.1.6)
Using dmg (2.2.0)
E, [2014-05-08T17:11:51.478582 #16013] ERROR -- : Actor crashed!
NoMethodError: undefined method `cookbook' for nil:NilClass
    /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/installer.rb:95:in `install'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
Using my_cookbook (0.1.0) from source at .
Using jenkins (2.0.2)
/Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/installer.rb:95:in `install': undefined method `cookbook' for nil:NilClass (NoMethodError)
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:92:in `value'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/pool_manager.rb:41:in `_send_'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/pool_manager.rb:123:in `method_missing'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/future.rb:104:in `value'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/celluloid-0.16.0.pre/lib/celluloid/future.rb:68:in `value'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/installer.rb:129:in `map'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/installer.rb:129:in `install_from_lockfile'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/installer.rb:37:in `run'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/berksfile.rb:371:in `install'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/cli.rb:143:in `install'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/cli.rb:52:in `dispatch'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/lib/berkshelf/cli.rb:27:in `execute!'
    from /Users/xgjo/.gem/ruby/2.1.1/gems/berkshelf-3.1.2/bin/berks:5:in `<top (required)>'
    from /Users/xgjo/.gem/ruby/2.1.1/bin/berks:23:in `load'
    from /Users/xgjo/.gem/ruby/2.1.1/bin/berks:23:in `<main>'
```

**Comment by lamont-granquist** [comment]
berkshelf 5.2.0 looks like this:

```
% berks install
Resolving cookbook dependencies...
Fetching 'three' from source at .
Fetching cookbook index from https://bogus.example.com...
/Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:604:in `initialize': getaddrinfo: nodename nor servname provided, or not known (bogus.example.com:443) (SocketError)
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:604:in `new'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:604:in `create_socket'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:18:in `create_socket'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:746:in `block in connect'
	from /Users/lamont/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/lamont/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:742:in `connect'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:504:in `query'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:174:in `query'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1240:in `do_get_block'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1017:in `block in do_request'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1012:in `do_request'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:854:in `request'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/httpclient.rb:36:in `call'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/request/retry.rb:116:in `call'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/berkshelf-api-client-3.0.0/lib/berkshelf/api_client/connection.rb:60:in `universe'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/berkshelf-5.2.0/lib/berkshelf/source.rb:49:in `build_universe'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/berkshelf-5.2.0/lib/berkshelf/installer.rb:21:in `block (2 levels) in build_universe'
```

stacktrace is ugly but the relevant information is right there.

PRs accepted to add a better error message.
