### ISSUE TITLE
Bad error message when retrieving cookbooks from chef-server location when there is no client.pem

### ISSUE THREAD

**Issue by capoferro** [berkshelf/berkshelf#1201]
(berks version 3.1.2)

The following error occurs when you are lacking a knife config and need to download cookbooks from the chef server referenced by an internal berks-api server:

```
/Users/fnenz/.rvm/gems/ruby-1.9.3-p545@global/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:34:in `terminate': task was terminated (Celluloid::Task::TerminatedError)

       from /Users/fnenz/.rvm/gems/ruby-1.9.3-p545@global/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:350:in `each'

       from /Users/fnenz/.rvm/gems/ruby-1.9.3-p545@global/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:350:in `cleanup'
```

When run with -d, the real error turns out to be:

```
Ridley::Errors::ClientKeyFileNotFoundOrInvalid client key is invalid or not found at: '/etc/chef/client.pem'D, [2014-05-13T19:58:09.937524 #94294] DEBUG -- :   Downloading not_system_ruby (0.1.9) from http://las1berkshelf.tf.riotgames.com:26200
```

Berkshelf should print out a proper error message saying it is missing necessary configuration rather than imploding.

**Comment by wjimenez5271** [comment]
@sethvargo re. work-around. where should the empty `knife.rb` exist?

**Comment by rbogdanoff** [comment]
@wjimenez5271 @sethvargo  re work-around.  the empty .chef/knife.rb does not work.  In berkshelf downloader.rb if the download is to come from ':chef_server' in the try_download method it needs the credential that it will pass to Ridley.  Ridley trys to get the client pem that is referenced in knife.rb. If it is not there it trys /etc/chef/client.pem.  In either case, a client pem must be found and if it is, it must be valid.  

When I get more time I am going to hack at this.  My issue is I am introducing a team of developers to Vagrant and Chef as a way to spin up a dev execution env and I need to get berkshef to download a cookbook from a berksapi server proxy that is in front of our chef server without a client.pem just like it does with the chef supermarket.  Hopefully I can share a suggested fix or enhancement soon

**Comment by rbogdanoff** [comment]
OK, I have hacked away at this for a bit.   Looks like the code was intentionally written to require an authenticated request to download a cookbook from a berksapi server.  A valid pem key is required..an empty knife.rb or an empty pem does not work as a workaround.

So, my question is now, how should it work?  Is the designed behavior to be 'authentication mandatory'?  Or could there be an enhancement to make this optional? 

My situation is I have open source chef with a berks api server pointing to it.  I have a use case where I provide a Berksfile and a Vagrantfile to developers so they can do a vagrant up and have a VM that will install a development runtime environment.  Most of these developers will not be developing cookbooks, they just want vagrant to converge them.  I REALLY do not want to give all these developers a pem + instructions about knife.rb, they will revolt, I need to provide the least amount of friction to get them to use this stuff and not have it look kudgie.  

For now I have had to, in the Berksfile, pull the cookbooks directly from our internal git repos and since  that will not resolve next level metadata.rb dependencies the Berkshelf list is very long.

**Comment by waziers** [comment]
This is problematic because it also means that you can't use the Berkshelf Api server with AWS Opsworks since they don't have a client.pem on the machine.

**Comment by jeffbyrnes** [comment]
@waziers that'd be b/c OpsWorks runs either in Chef Solo, or local Chef Client, mode: http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook.html. No `client.pem` needed, because there’s no server to talk to.

**Comment by pelletiermaxime** [comment]
Just had the same error with a use case very similar to @rbogdanoff. Fetching all cookbooks via git was very slow and made it complicated to have the right versions, so I tried setuping berks-api. Of course it worked perfectly on my machine... and then a developer tried it and got this error because he didn't have a knife setup :/.
Oh well, I'm going to wait for a non alpha version of the supermarket.
Thanks.

**Comment by craigske** [comment]
In my case, we have an internal chef server that we knife up cookbooks. We then use chef_zero (in my current case) to run vagrants. For dependency resolution, there is a berksapi server that is configured to resolve against the chef server as @jsirex detailed above. 

The problem exists even though I'm not trying to knife anything up to the chef server. I have my berksfile pointed at the berksapi server. I still get this error for some cookbooks and not for others. Actually, it seems to mostly happen when I have cookbooks that depend on other cookbooks in the chef server. I suspect the dependency resolution process in the berksapi hands back the chef server source, instead of vending it itself. Need to verify though

**Comment by lamont-granquist** [comment]
berks-api is deprecated abandonware at this point, supermarket or minimart are the right tools to use.  for hitting the chef-server api you absolutely must have a client.pem file and do an authenticated request (hopefully it is obvious why).

the useful part of this issue appears to boil down to "bad error message when client.pem is not present".
