### ISSUE TITLE
Retreiving cookbook via berks-api without github entry in config.json errors

### ISSUE THREAD

**Issue by rhysrhaven** [berkshelf/berkshelf#1210]
We have an internal github enterprise server configured as an endpoint in berkshelf-api:

```
  "endpoints": [
    {
      "type": "github",
      "options": {
        "organization": "cookbooks",
        "api_endpoint": "https://git.acme.com/api/v3",
        "web_endpoint": "https://git.acme.com",
        "ssl_verify": true
      }
    }
  ]
```

This information should be enough to download the cookbook as our enterprise server is world readable. But it crashes, seemingly because the error class isn't included.

```
$ berks install
Resolving cookbook dependencies...
Fetching 'apt-acme' from source at .
Fetching cookbook index from http://berkshelf.acme.com...
Installing apt (2.4.0) from http://berkshelf.acme.com ([github] https://git.acme.com/cookbooks/apt)
Using apt-acme (0.1.0) from source at .
E, [2014-05-22T17:09:35.982590 #8761] ERROR -- : Actor crashed!
NameError: uninitialized constant Berkshelf::Downloader::ConfigurationError
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:82:in `try_download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:33:in `block in download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:32:in `each'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:32:in `download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:101:in `install'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:82:in `try_download': uninitialized constant Berkshelf::Downloader::ConfigurationError (NameError)
```

The error is here: https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/downloader.rb#L81

If the error function worked, it would have said: "Missing github endpoint configuration for https://git.acme.com" Which I guess is berkshelf wanting to lookup credential information for the specified github server the API told it to download from.

My workaround is simply to take the JSON config in the berkshelf-api and copy it to the client. But shouldn't this just work without configuring my local berkshelf if I don't need any more information than what the API has already provided?

**Comment by lamont-granquist** [comment]
closing old inactive issues
