### ISSUE TITLE
BERKSHELF_PATH must be an absolute path to checkout git-based Cookbooks

### ISSUE THREAD

**Issue by ampledata** [berkshelf/berkshelf#1256]
Berkshelf cannot checkout git-based Cookbooks to a custom BERKSHELF_PATH that's not specified as an absolute path.
## To Reproduce
1. Create a Berksfile containing:
   
   ``` ruby
   source 'http://api.berkshelf.com'
   cookbook 'apt', github: 'opscode-cookbooks/apt'
   ```
2. Install **apt** Cookbook using Berkshelf with to a **BERKSHELF_PATH**: 
   
   ``` sh
   $ BERKSHELF_DEBUG=1 BERKSHELF_PATH='example_path' berks install -d
   ```
## Expected Result
1. Cookbook **apt** should be checked-out to **BERKSHELF_PATH**.
## Actual Result
1. Berkshelf raises the following exception:

``` sh
$ BERKSHELF_DEBUG=1 BERKSHELF_PATH=example_path berks install -d
I, [2014-07-09T15:33:01.141065 #61791]  INFO -- : Reducing lockfile
D, [2014-07-09T15:33:01.141167 #61791] DEBUG -- : Current lockfile:
D, [2014-07-09T15:33:01.141254 #61791] DEBUG -- : 
D, [2014-07-09T15:33:01.141346 #61791] DEBUG -- :   DEPENDENCIES
D, [2014-07-09T15:33:01.141370 #61791] DEBUG -- :   
D, [2014-07-09T15:33:01.141388 #61791] DEBUG -- :   GRAPH
D, [2014-07-09T15:33:01.141411 #61791] DEBUG -- : 
D, [2014-07-09T15:33:01.141442 #61791] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2014-07-09T15:33:01.141512 #61791] DEBUG -- : Removing transitive dependencies
D, [2014-07-09T15:33:01.141560 #61791] DEBUG -- :   Checking apt (>= 0.0.0)
D, [2014-07-09T15:33:01.141589 #61791] DEBUG -- :     Skipping (not graphed)
D, [2014-07-09T15:33:01.141608 #61791] DEBUG -- : New lockfile:
D, [2014-07-09T15:33:01.141626 #61791] DEBUG -- : 
D, [2014-07-09T15:33:01.141651 #61791] DEBUG -- :   DEPENDENCIES
D, [2014-07-09T15:33:01.141670 #61791] DEBUG -- :   
D, [2014-07-09T15:33:01.141688 #61791] DEBUG -- :   GRAPH
D, [2014-07-09T15:33:01.141709 #61791] DEBUG -- : 
Resolving cookbook dependencies...
I, [2014-07-09T15:33:01.141822 #61791]  INFO -- : Checking if lockfile is trusted
D, [2014-07-09T15:33:01.141869 #61791] DEBUG -- : Checking apt (>= 0.0.0)
D, [2014-07-09T15:33:01.141986 #61791] DEBUG -- :   Not in lockfile - cannot be trusted!
I, [2014-07-09T15:33:01.142022 #61791]  INFO -- : Installing from universe
Fetching 'apt' from git://github.com/opscode-cookbooks/apt.git (at master)
Git error: command `git fetch --force --tags "example_path/.cache/git/44109d6e3dc4889212f961596306b3cf32a5dfd2"` failed. If this error persists, try removing the cache directory at 'example_path/.cache/git/44109d6e3dc4889212f961596306b3cf32a5dfd2'.Output from the command:

fatal: 'example_path/.cache/git/44109d6e3dc4889212f961596306b3cf32a5dfd2' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/mixin/git.rb:23:in `git'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/locations/git.rb:58:in `block in install'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/locations/git.rb:57:in `chdir'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/locations/git.rb:57:in `install'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:179:in `block in download_locations'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:176:in `each'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:176:in `download_locations'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:149:in `install_from_universe'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:39:in `run'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/berksfile.rb:371:in `install'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:143:in `install'        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:52:in `dispatch'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:27:in `execute!'
        /Users/gba/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/bin/berks:5:in `<top (required)>'
        /Users/gba/.rbenv/versions/2.1.1/bin/berks:23:in `load'
        /Users/gba/.rbenv/versions/2.1.1/bin/berks:23:in `<main>'
```
## Work-around
1. Specify **BERKSHELF_PATH** as an absolute path.

``` sh
$ BERKSHELF_DEBUG=1 BERKSHELF_PATH="`pwd`/example_path" berks install -d
I, [2014-07-09T15:33:48.369811 #61929]  INFO -- : Reducing lockfile
D, [2014-07-09T15:33:48.369912 #61929] DEBUG -- : Current lockfile:
D, [2014-07-09T15:33:48.369936 #61929] DEBUG -- : 
D, [2014-07-09T15:33:48.370005 #61929] DEBUG -- :   DEPENDENCIES
D, [2014-07-09T15:33:48.370025 #61929] DEBUG -- :   
D, [2014-07-09T15:33:48.370046 #61929] DEBUG -- :   GRAPH
D, [2014-07-09T15:33:48.370064 #61929] DEBUG -- : 
D, [2014-07-09T15:33:48.370081 #61929] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2014-07-09T15:33:48.370099 #61929] DEBUG -- : Removing transitive dependencies
D, [2014-07-09T15:33:48.370153 #61929] DEBUG -- :   Checking apt (>= 0.0.0)
D, [2014-07-09T15:33:48.370185 #61929] DEBUG -- :     Skipping (not graphed)
D, [2014-07-09T15:33:48.370221 #61929] DEBUG -- : New lockfile:
D, [2014-07-09T15:33:48.370239 #61929] DEBUG -- : 
D, [2014-07-09T15:33:48.370269 #61929] DEBUG -- :   DEPENDENCIES
D, [2014-07-09T15:33:48.370302 #61929] DEBUG -- :   
D, [2014-07-09T15:33:48.370357 #61929] DEBUG -- :   GRAPH
D, [2014-07-09T15:33:48.370390 #61929] DEBUG -- : 
Resolving cookbook dependencies...
I, [2014-07-09T15:33:48.370523 #61929]  INFO -- : Checking if lockfile is trusted
D, [2014-07-09T15:33:48.370573 #61929] DEBUG -- : Checking apt (>= 0.0.0)
D, [2014-07-09T15:33:48.370612 #61929] DEBUG -- :   Not in lockfile - cannot be trusted!
I, [2014-07-09T15:33:48.370691 #61929]  INFO -- : Installing from universe
Fetching 'apt' from git://github.com/opscode-cookbooks/apt.git (at master)
D, [2014-07-09T15:33:48.818718 #61929] DEBUG -- :   Creating a resolver
Fetching cookbook index from http://api.berkshelf.com...
D, [2014-07-09T15:33:50.047924 #61929] DEBUG -- : ==> parsing Chef response body as JSON
D, [2014-07-09T15:33:50.219671 #61929] DEBUG -- :   Adding explicit dependency on apt (2.4.1) '/Users/gba/t/berks/example_path/cookbooks/apt-ac1917c66a9d67fb4a0afeffaa92195b7385887e'
D, [2014-07-09T15:33:50.219858 #61929] DEBUG -- :   Starting resolution...
I, [2014-07-09T15:33:50.601563 #61929]  INFO -- : Installing apt (2.4.1)
D, [2014-07-09T15:33:50.601638 #61929] DEBUG -- :   Already installed - skipping install
Using apt (2.4.1) from git://github.com/opscode-cookbooks/apt.git (at master)
D, [2014-07-09T15:33:50.601825 #61929] DEBUG -- :   Finished resolving, calculating locks
D, [2014-07-09T15:33:50.601878 #61929] DEBUG -- :   New locks
D, [2014-07-09T15:33:50.601934 #61929] DEBUG -- :     apt (2.4.1)
```

**Comment by eric-tucker** [comment]
Using version 4.0.1 (bundled with the ChefDK) I'm still seeing this issue.  It's easily reproducible by switching between a relative path and an absolute path:

```
[etucker: git_repo_name]$ export BERKSHELF_PATH=../../berkshelf && berks vendor --berksfile=base_berksfile berks-cookbooks
Resolving cookbook dependencies...
Fetching 'base' from git@bitbucket.org:orgname/git_repo_name (at master/cookbooks/base)
Git error: command `git fetch --force --tags "/berkshelf/.cache/git/d251639f4f235be74b01804d4012969464cc6a3a"` failed. If this error persists, try removing the cache directory at '/berkshelf/.cache/git/d251639f4f235be74b01804d4012969464cc6a3a'.Output from the command:

fatal: '/berkshelf/.cache/git/d251639f4f235be74b01804d4012969464cc6a3a' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.




[etucker: git_repo_name]$ export BERKSHELF_PATH=$HOME/berkshelf && berks vendor --berksfile=base_berksfile berks-cookbooks
Resolving cookbook dependencies...
Fetching 'base' from git@bitbucket.org:orgname/git_repo_name (at master/cookbooks/base)
Fetching 'cloudwatch_logs' from git@bitbucket.org:orgname/git_repo_name (at master/cookbooks/cloudwatch_logs)
...
```
