### ISSUE TITLE
Error installing berkshelf on FreeBSD 10.0-RELEASE

### ISSUE THREAD

**Issue by anandsuresh** [berkshelf/berkshelf#1280]
Running Ruby 1.9.3@547 on FreeBSD 10.0-RELEASE on Vagrant/Virtualbox. Here is the log for the the command `gem install --no-ri --no-rdoc berkshelf -v 3.1.5`

```
ERROR:  Error installing berkshelf:
    ERROR: Failed to build gem native extension.

        /usr/local/bin/ruby19 extconf.rb
-> sh /usr/local/lib/ruby/gems/1.9/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3/configure --prefix=/usr/local/lib/ruby/gems/1.9/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode --disable-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disable-doc-docset --disable-qt --disable-examples --disable-flatzinc
checking for the host operating system... Linux
checking for g++... no
checking for c++... c++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes
checking for gcc... no
checking for cc... cc
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for diff... ok
checking for tar... ok
checking for make... ok
checking for sed... ok
checking for perl... ok
checking how to run the C++ preprocessor... c++ -E
checking for rc.exe... no
checking whether to build with Visual Studio resource files... no
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ext/hash_map usability... yes
checking ext/hash_map presence... yes
checking for ext/hash_map... yes
checking Whether to build for different architectures... no
checking for user-defined library name prefix... no
checking for user-defined library name suffix... no
checking whether to build static libraries... no
checking whether to build shared libraries... yes
checking whether to build with debug symbols and assertions... no
checking whether to optimize for code size... no
checking whether to build with support for finding memory leaks... no
checking whether to build with auditing code... no
checking whether to build with profiling information... no
checking whether to build with gcov support... no
checking size of int... 4
checking if int has at least 32 bit... yes
checking if doubles have a big enough mantissa... yes
checking for unistd.h... (cached) yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking whether c++ accepts -fPIC... yes
checking whether cc accepts -fPIC... yes
checking whether c++ accepts -Wextra... yes
checking whether cc accepts -Wextra... yes
checking whether c++ accepts -Wall... yes
checking whether cc accepts -Wall... yes
checking whether c++ accepts -pipe... yes
checking whether cc accepts -pipe... yes
checking whether c++ accepts -ggdb... yes
checking for __builtin_ffsl... no
checking whether to use gcc visibility attributes... yes
checking whether c++ accepts -fvisibility=hidden... yes
checking if compiler supports forced inlining... yes
checking whether c++ accepts -O3... yes
checking whether cc accepts -O3... yes
checking whether c++ accepts -fno-strict-aliasing... yes
checking whether cc accepts -fno-strict-aliasing... yes
checking whether c++ accepts -ffast-math... yes
checking whether cc accepts -ffast-math... yes
checking whether c++ accepts -mthreads... no
checking whether cc accepts -mthreads... no
checking whether c++ accepts -Qunused-arguments... yes
checking whether cc accepts -Qunused-arguments... yes
checking for dot... no
checking whether to enable graphs in the documentation... no
checking whether to enable the documentation search engine... no
checking whether to generate a doxygen tagfile... no
checking whether to build compressed html documentation... no
checking whether to build docset documentation for XCode... no
checking whether to build the set variables library... yes
checking whether to build the int variables library... yes
checking for qmake-qt4... no
checking for qmake... no
checking for moc-qt4... no
checking for moc... no
checking whether to build with Qt support... no
checking whether to build Gist... no
checking for flex... flex
checking whether we have at least flex 2.5.33... yes
checking for bison... no
checking whether we have at least bison 2.3... no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking whether to build driver... yes
checking whether to build flatzinc... no
checking whether to build driver... yes
checking whether to build examples... no
checking whether to build minimodel... yes
checking whether to build search... yes
/usr/local/lib/ruby/gems/1.9/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3/configure: 11561: Syntax error: word unexpected (expecting ")")
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
    from extconf.rb:97:in `chdir'
    from extconf.rb:97:in `run'
    from extconf.rb:104:in `<main>'


Gem files will remain installed in /usr/local/lib/ruby/gems/1.9/gems/dep-selector-libgecode-1.0.2 for inspection.
Results logged to /usr/local/lib/ruby/gems/1.9/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/gem_make.out
```

**Comment by hectcastro** [comment]
Just went through a similar process on FreeBSD 10.1. First had to downgrade the `gecode` port for `3.7.3`:

```bash
$ sudo portdowngrade devel/gecode r345033
```
