### ISSUE TITLE
Multiple sources causes Berkshelf to hang

### ISSUE THREAD

**Issue by chrishenry** [berkshelf/berkshelf#1304]
Hi,

My team uses multiple sources in our `Berksfile`s. 

``` ruby
source 'http://berksapi.our-own-domain-in-front-of-our.chef.server.co.uk/'
source 'https://supermarket.getchef.com'
```

As of yesterday (9.16.14), running a `berks update` or `berks install` will hang forever. Here's some sample output, with the debug flag. Additionally, the process will not respond to ^C, which may or may not be important.

``` bash
 |1.9.3-p448| Beardtop in ~/Code/behanceops/chef/cookbooks/bepyinspector
± |feature-initial ✗| → set DEBUG_RESOLVER=1

 |1.9.3-p448| Beardtop in ~/Code/behanceops/chef/cookbooks/bepyinspector
± |feature-initial ✗| → bx berks update -d
I, [2014-09-17T10:21:22.291078 #78944]  INFO -- : Updating cookbooks
D, [2014-09-17T10:21:22.291157 #78944] DEBUG -- :   Unlocking all the things!
I, [2014-09-17T10:21:22.315432 #78944]  INFO -- : Reducing lockfile
D, [2014-09-17T10:21:22.315522 #78944] DEBUG -- : Current lockfile:
D, [2014-09-17T10:21:22.315550 #78944] DEBUG -- :
D, [2014-09-17T10:21:22.315592 #78944] DEBUG -- :   DEPENDENCIES
D, [2014-09-17T10:21:22.315616 #78944] DEBUG -- :
D, [2014-09-17T10:21:22.315638 #78944] DEBUG -- :   GRAPH
D, [2014-09-17T10:21:22.315660 #78944] DEBUG -- :
D, [2014-09-17T10:21:22.315681 #78944] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2014-09-17T10:21:22.315702 #78944] DEBUG -- : Removing transitive dependencies
D, [2014-09-17T10:21:22.315753 #78944] DEBUG -- :   Checking bejenkins-slave (>= 0.0.0)
D, [2014-09-17T10:21:22.315783 #78944] DEBUG -- :     Skipping (not graphed)
D, [2014-09-17T10:21:22.315810 #78944] DEBUG -- :   Checking bepyinspector (>= 0.0.0)
D, [2014-09-17T10:21:22.315831 #78944] DEBUG -- :     Skipping (not graphed)
D, [2014-09-17T10:21:22.315852 #78944] DEBUG -- : New lockfile:
D, [2014-09-17T10:21:22.315872 #78944] DEBUG -- :
D, [2014-09-17T10:21:22.315897 #78944] DEBUG -- :   DEPENDENCIES
D, [2014-09-17T10:21:22.315919 #78944] DEBUG -- :
D, [2014-09-17T10:21:22.315940 #78944] DEBUG -- :   GRAPH
D, [2014-09-17T10:21:22.315960 #78944] DEBUG -- :
Resolving cookbook dependencies...
I, [2014-09-17T10:21:22.316021 #78944]  INFO -- : Checking if lockfile is trusted
D, [2014-09-17T10:21:22.316057 #78944] DEBUG -- : Checking bejenkins-slave (>= 0.0.0)
D, [2014-09-17T10:21:22.316083 #78944] DEBUG -- :   Not in lockfile - cannot be trusted!
I, [2014-09-17T10:21:22.316106 #78944]  INFO -- : Installing from universe
Fetching 'bejenkins-slave' from source at ../bejenkins-slave
D, [2014-09-17T10:21:22.317315 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stufff/chef/cookbooks/bejenkins-slave/chefignore'
Fetching 'bepyinspector' from source at .
D, [2014-09-17T10:21:22.321046 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stufff/chef/chefignore'
D, [2014-09-17T10:21:22.323195 #78944] DEBUG -- :   Creating a resolver
Fetching cookbook index from http://berksapi.our-own-domain-in-front-of-our.chef.server.co.uk/...
Fetching cookbook index from https://supermarket.getchef.com...
D, [2014-09-17T10:21:22.989614 #78944] DEBUG -- : ==> parsing Chef response body as JSON
D, [2014-09-17T10:21:24.469398 #78944] DEBUG -- : ==> parsing Chef response body as JSON
D, [2014-09-17T10:21:24.643726 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stufff/chef/cookbooks/bejenkins-slave/chefignore'
D, [2014-09-17T10:21:24.646281 #78944] DEBUG -- :   Adding explicit dependency on bejenkins-slave (0.1.2) '/path/to/stufff/chef/cookbooks/bejenkins-slave'
D, [2014-09-17T10:21:24.647445 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stufff/chef/chefignore'
D, [2014-09-17T10:21:24.649606 #78944] DEBUG -- :   Adding explicit dependency on bepyinspector (0.0.1) '/path/to/stufff/chef/cookbooks/bepyinspector'
D, [2014-09-17T10:21:24.649717 #78944] DEBUG -- :   Starting resolution...
D, [2014-09-17T10:21:24.655357 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/beami-1.1.7/chefignore'
D, [2014-09-17T10:21:24.658151 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/bebootstrap-4.0.5/chefignore'
D, [2014-09-17T10:21:24.672742 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/bejava-0.3.8/chefignore'
D, [2014-09-17T10:21:24.676452 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/bepython-0.5.0/chefignore'
D, [2014-09-17T10:21:24.680114 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/besudoers-0.1.5/chefignore'
D, [2014-09-17T10:21:24.719297 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/beusers-2.1.1/chefignore'
D, [2014-09-17T10:21:24.729688 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/iptables-ng-2.0.3/chefignore'
D, [2014-09-17T10:21:24.733611 #78944] DEBUG -- : Using 'chefignore' at '/path/to/stuff/.berkshelf/cookbooks/motd-0.1.2/chefignore'
....
wait an extremely long time....
....
^Z
[5]+  Stopped                 bundle exec berks update -d
```

Is there a possibility the resolver is seeing overlaps between our own berksapi and the supermarket? In our experiments, we were able to see either full resolution by removing supermarket, or a can not resolve error in the case where we removed our own berksapi.

Lastly, is there a way to see any more debug output from the resolver? I've tried setting the `set DEBUG_RESOLVER=1` env var, but that doesn't seem to add any insight into what the resolver is doing.

**Comment by amaltson** [comment]
@reset not sure if I should comment here or create a new issue, but I'm having the same issue right now with Berkshelf `4.0.1`. I have the resolution time out:

```
D, [2015-11-30T15:07:53.399562 #25156] DEBUG -- : Using 'chefignore' at '/Users/arthur/work/chef/cookbookB/chefignore'
D, [2015-11-30T15:07:53.426414 #25156] DEBUG -- :   Creating a resolver
Fetching cookbook index from https://supermarket.chef.io...
Fetching cookbook index from http://local.supermarket...
D, [2015-11-30T15:07:53.498954 #25156] DEBUG -- : ==> parsing Chef response body as JSON
D, [2015-11-30T15:07:59.373128 #25156] DEBUG -- : ==> parsing Chef response body as JSON
D, [2015-11-30T15:07:59.628007 #25156] DEBUG -- : Using 'chefignore' at '/Users/arthur/work/chef/cookbookB/chefignore'
D, [2015-11-30T15:07:59.638490 #25156] DEBUG -- :   Adding explicit dependency on cookbookB (1.9.0) '/Users/arthur/work/chef/cookbookB'
D, [2015-11-30T15:07:59.638630 #25156] DEBUG -- :   Starting resolution...
D, [2015-11-30T15:07:59.662137 #25156] DEBUG -- : Using 'chefignore' at '/Users/arthur/.berkshelf/cookbooks/elasticsearch-0.3.14/chefignore'
D, [2015-11-30T15:07:59.712579 #25156] DEBUG -- : Using 'chefignore' at '/Users/arthur/.berkshelf/cookbooks/helper_cookbook-2.1.1/chefignore'
D, [2015-11-30T15:07:59.717878 #25156] DEBUG -- : Using 'chefignore' at '/Users/arthur/.berkshelf/cookbooks/cookbookA-0.1.0/chefignore'
D, [2015-11-30T15:07:59.728012 #25156] DEBUG -- : Using 'chefignore' at '/Users/arthur/.berkshelf/cookbooks/internal_redis-1.0.3/chefignore'
The dependency constraints could not be solved in the time allotted.
Unable to find a solution for demands: helper_cookbook (~> 2.1), cookbookB (1.9.0)
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/resolver.rb:83:in `rescue in resolve'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/resolver.rb:73:in `resolve'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:175:in `install_from_universe'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:39:in `run'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:374:in `install'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:143:in `install'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
        /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
        /opt/chefdk/bin/berks:44:in `load'
        /opt/chefdk/bin/berks:44:in `<main>'
```

For this specific cookbook, there aren't any public supermarket dependencies, so when I remove public supermarket, it resolves instantly and correctly.

```diff
source 'http://supermarket.local'
- source 'https://supermarket.chef.io'

metadata

group :test do
  cookbook 'helper_cookbook', '~> 2.1'
end
```

I've also tried resolving with `DEBUG_RESOLVER=1`, but as @chrishenry noted, I didn't see any additional information during the resolution.

Thanks in advance!

**Comment by rodrigdav** [comment]
I am seeing the same issue that @amaltson is seeing.

**Comment by moofrank** [comment]
Same here. We are running a Jenkins job which stopped being able to build 2-3 weeks ago. 
Any chance it is a broken cookbook we are hitting? We are winding our way through the Rackspace elkstack + logstash + elasticsearch dependency graph.

**Comment by rodrigdav** [comment]
This is really killing us right now.  so much so that we probably have to abandon this tool chain.

**Comment by amaltson** [comment]
@rodrigdav this is really killing us too. It's been solved in [Berkshelf master](https://discourse.chef.io/t/strategies-for-debugging-with-dependency-resolution-issues/7366/4?u=amaltson) using the Ruby solver. We're moving to Policyfiles to get around this since it affects our `chef-client` runs too.

If you're only experiencing an issue when using Berkshelf, consider using the latest master.

**Comment by rodrigdav** [comment]
@amaltson worked like a charm

**Comment by amaltson** [comment]
@rodrigdav fantastic :+1:. I still hope this makes it's way into a release very soon and the new Ruby solver becomes default.
