### ISSUE TITLE
v3.2.0 seems to break some dependency resolution in Test Kitchen runs

### ISSUE THREAD

**Issue by jeffbyrnes** [berkshelf/berkshelf#1337]
After upgrading a cookbook to use Berkshelf v3.2.0, I seem to be having trouble using Test Kitchen to converge a Vagrant VM. I am using TK bleeding edge (test-kitchen/test-kitchen@5240ce06acc4d23594c82d54c47f224d3d677d96 as of this writing), but that’s been working well with Berkshelf v3.1.5.

If I downgrade back to Berkshelf v3.1.5, all is well again.

Some context:

``` ruby
# metadata.rb

depends 'apt'
depends 'openssl'
depends 'logrotate', '~> 1.5'
depends 'et_fog', '~> 1.0'
depends 'stunnel', '~> 2.0'
depends 'certificate', '~> 0.5'
depends 'newrelic_meetme_plugin', '~> 0.0.3'
depends 'sudo', '~> 2.7'
depends 'et_users', '~> 1.4'
depends 'et_security', '~> 1.0'
```

``` ruby
# Berksfile

source 'https://supermarket.getchef.com'
source 'https://berks.evertrue.com'

metadata

group :integration do
  cookbook 'et_nginx'
  cookbook 'et_hostname'
  cookbook 'et_logger', '~> 3.1'
end
```

Relevant trace from `bundle exec kitchen test -l debug`:

```
I, [2014-11-04T17:07:00.706175 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
I, [2014-11-04T17:07:00.706200 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
I, [2014-11-04T17:07:00.706390 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: Initiating POST to http://localhost:8889/environments/dev/cookbook_versions
I, [2014-11-04T17:07:00.706429 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: ---- HTTP Request Header Data: ----
I, [2014-11-04T17:07:00.706456 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: Content-Type: application/json
I, [2014-11-04T17:07:00.706482 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: Accept: application/json
I, [2014-11-04T17:07:00.706642 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
I, [2014-11-04T17:07:00.706760 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
I, [2014-11-04T17:07:00.706876 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-USERID: default-ubuntu-1204
I, [2014-11-04T17:07:00.707001 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-TIMESTAMP: 2014-11-04T22:07:00Z
I, [2014-11-04T17:07:00.707031 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-CONTENT-HASH: …
I, [2014-11-04T17:07:00.707056 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-AUTHORIZATION-1: …
I, [2014-11-04T17:07:00.707080 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-AUTHORIZATION-2: …
I, [2014-11-04T17:07:00.707121 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-AUTHORIZATION-3: …
I, [2014-11-04T17:07:00.707148 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-AUTHORIZATION-4: …
I, [2014-11-04T17:07:00.707172 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-AUTHORIZATION-5: …
I, [2014-11-04T17:07:00.707195 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-OPS-AUTHORIZATION-6: …
I, [2014-11-04T17:07:00.708574 #17884]  INFO -- default-ubuntu-1204: DEBUG: HOST: localhost:8889
I, [2014-11-04T17:07:00.708649 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: X-REMOTE-REQUEST-ID: e4bc8057-fa49-4dc1-aa9c-9b11a6327557
I, [2014-11-04T17:07:00.708695 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: Content-Length: 107
I, [2014-11-04T17:07:00.708724 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: ---- End HTTP Request Header Data ----
I, [2014-11-04T17:07:00.708936 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:00+00:00] DEBUG: POST organizations/chef/environments/dev/cookbook_versions
I, [2014-11-04T17:07:00.708980 #17884]  INFO -- default-ubuntu-1204: --- POST BODY ---
I, [2014-11-04T17:07:00.709012 #17884]  INFO -- default-ubuntu-1204: {"run_list":["et_logger","et_nginx::default","et_hostname","et_users","et_haproxy","et_haproxy::newrelic"]}
I, [2014-11-04T17:07:00.709038 #17884]  INFO -- default-ubuntu-1204: --- END POST BODY ---
I, [2014-11-04T17:07:02.640399 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: #<ChefZero::RestErrorResponse: ChefZero::RestErrorResponse>
I, [2014-11-04T17:07:02.640479 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:42:in `post'
I, [2014-11-04T17:07:02.640534 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/rest_base.rb:29:in `call'
I, [2014-11-04T17:07:02.640589 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/rest_router.rb:23:in `call'
I, [2014-11-04T17:07:02.640626 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/server.rb:443:in `block in app'
I, [2014-11-04T17:07:02.640658 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
I, [2014-11-04T17:07:02.640696 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
I, [2014-11-04T17:07:02.640730 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
I, [2014-11-04T17:07:02.640762 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
I, [2014-11-04T17:07:02.640794 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
I, [2014-11-04T17:07:02.641295 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: 
I, [2014-11-04T17:07:02.641351 #17884]  INFO -- default-ubuntu-1204: --- RESPONSE (412) ---
I, [2014-11-04T17:07:02.641389 #17884]  INFO -- default-ubuntu-1204: {
I, [2014-11-04T17:07:02.641422 #17884]  INFO -- default-ubuntu-1204:   "error": [
I, [2014-11-04T17:07:02.641456 #17884]  INFO -- default-ubuntu-1204:     "Could not satisfy version constraints for: certificate"
I, [2014-11-04T17:07:02.641489 #17884]  INFO -- default-ubuntu-1204:   ]
I, [2014-11-04T17:07:02.641770 #17884]  INFO -- default-ubuntu-1204: }
I, [2014-11-04T17:07:02.641812 #17884]  INFO -- default-ubuntu-1204: --- END RESPONSE ---
I, [2014-11-04T17:07:02.642315 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: ---- HTTP Status and Header Data: ----
I, [2014-11-04T17:07:02.642640 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: HTTP 1.1 412 Precondition Failed 
I, [2014-11-04T17:07:02.642972 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: content-type: application/json
I, [2014-11-04T17:07:02.643288 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: server: chef-zero
I, [2014-11-04T17:07:02.643550 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: date: Tue, 04 Nov 2014 22:07:02 GMT
I, [2014-11-04T17:07:02.643597 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: content-length: 81
I, [2014-11-04T17:07:02.643859 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: connection: close
I, [2014-11-04T17:07:02.643932 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: ---- End HTTP Status/Header Data ----
I, [2014-11-04T17:07:02.644281 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
I, [2014-11-04T17:07:02.644365 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Content-Length validated correctly.
I, [2014-11-04T17:07:02.644674 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
I, [2014-11-04T17:07:02.644721 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
I, [2014-11-04T17:07:02.644898 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
I, [2014-11-04T17:07:02.645055 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
I, [2014-11-04T17:07:02.645331 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
I, [2014-11-04T17:07:02.645605 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
I, [2014-11-04T17:07:02.645683 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] INFO: HTTP Request Returned 412 Precondition Failed : Could not satisfy version constraints for: certificate
I, [2014-11-04T17:07:02.645975 #17884]  INFO -- default-ubuntu-1204: 
I, [2014-11-04T17:07:02.646034 #17884]  INFO -- default-ubuntu-1204: ================================================================================
I, [2014-11-04T17:07:02.646102 #17884]  INFO -- default-ubuntu-1204: Error Resolving Cookbooks for Run List:
I, [2014-11-04T17:07:02.646388 #17884]  INFO -- default-ubuntu-1204: ================================================================================
I, [2014-11-04T17:07:02.646569 #17884]  INFO -- default-ubuntu-1204: 
I, [2014-11-04T17:07:02.646606 #17884]  INFO -- default-ubuntu-1204: Missing Cookbooks:
I, [2014-11-04T17:07:02.646858 #17884]  INFO -- default-ubuntu-1204: ------------------
I, [2014-11-04T17:07:02.646895 #17884]  INFO -- default-ubuntu-1204: Could not satisfy version constraints for: certificate
I, [2014-11-04T17:07:02.646924 #17884]  INFO -- default-ubuntu-1204: 
I, [2014-11-04T17:07:02.647151 #17884]  INFO -- default-ubuntu-1204: 
I, [2014-11-04T17:07:02.647201 #17884]  INFO -- default-ubuntu-1204: ------------------
I, [2014-11-04T17:07:02.647231 #17884]  INFO -- default-ubuntu-1204: * et_logger
I, [2014-11-04T17:07:02.647383 #17884]  INFO -- default-ubuntu-1204: * et_nginx::default
I, [2014-11-04T17:07:02.647415 #17884]  INFO -- default-ubuntu-1204: * et_hostname
I, [2014-11-04T17:07:02.647462 #17884]  INFO -- default-ubuntu-1204: * et_users
I, [2014-11-04T17:07:02.647756 #17884]  INFO -- default-ubuntu-1204: * et_haproxy
I, [2014-11-04T17:07:02.647817 #17884]  INFO -- default-ubuntu-1204: * et_haproxy::newrelic
I, [2014-11-04T17:07:02.648118 #17884]  INFO -- default-ubuntu-1204: 
I, [2014-11-04T17:07:02.648349 #17884]  INFO -- default-ubuntu-1204: [2014-11-04T22:07:02+00:00] DEBUG: Re-raising exception: Net::HTTPServerException - 412 "Precondition Failed "
I, [2014-11-04T17:07:02.648388 #17884]  INFO -- default-ubuntu-1204: /opt/chef/embedded/lib/ruby/1.9.1/net/http.rb:2633:in `error!'
I, [2014-11-04T17:07:02.648416 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/http.rb:145:in `request'
I, [2014-11-04T17:07:02.648443 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/http.rb:126:in `post'
I, [2014-11-04T17:07:02.648470 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/policy_builder/expand_node_object.rb:168:in `sync_cookbooks'
I, [2014-11-04T17:07:02.648497 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/policy_builder/expand_node_object.rb:66:in `setup_run_context'
I, [2014-11-04T17:07:02.648523 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:265:in `setup_run_context'
I, [2014-11-04T17:07:02.648550 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:429:in `do_run'
I, [2014-11-04T17:07:02.648576 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:213:in `block in run'
I, [2014-11-04T17:07:02.648602 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:207:in `fork'
I, [2014-11-04T17:07:02.648629 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:207:in `run'
I, [2014-11-04T17:07:02.648655 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application.rb:236:in `run_chef_client'
I, [2014-11-04T17:07:02.648682 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/client.rb:338:in `block in run_application'
I, [2014-11-04T17:07:02.648709 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/client.rb:327:in `loop'
I, [2014-11-04T17:07:02.649304 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/client.rb:327:in `run_application'
I, [2014-11-04T17:07:02.649378 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application.rb:55:in `run'
I, [2014-11-04T17:07:02.649414 #17884]  INFO -- default-ubuntu-1204:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/bin/chef-client:26:in `<top (required)>'
I, [2014-11-04T17:07:02.649443 #17884]  INFO -- default-ubuntu-1204:   /usr/bin/chef-client:23:in `load'
I, [2014-11-04T17:07:02.649473 #17884]  INFO -- default-ubuntu-1204:   /usr/bin/chef-client:23:in `<main>'
```

**Comment by thommay** [comment]
Hi @jeffbyrnes; is this issue still valid? We're doing some tidying up and want to understand what the state of things is…

**Comment by lamont-granquist** [comment]
the problem is the cookbook is using metadata.rb that does an IO.read() to populate the version.

if there's an issue where some tooling is still favoring metadata.rb over metadata.json (and would thereby be hitting the terrible `rescue 0.0.1` in that cookbook) then an explicit issue should really get cut against the appropriate tooling.

**Comment by jeffbyrnes** [comment]
@thommay I’m no longer using this cookbook, so I can’t say, but it’s been a few years, so I think it’s safe to leave it closed.
