### ISSUE TITLE
Multiple errors in debug log but can upload with knife

### ISSUE THREAD

**Issue by cstewart87** [berkshelf/berkshelf#1340]
**My debug log shows multiple errors and I'm having troubles deciphering.**  The errors are:
- In DEBUG response body: `"{\"error\":[\"Cannot find a cookbook named apache2 with version 2.0.0\"]}"` - maybe just check for whether cookbook already exists on server?
- Claimed syntax error (confused here because this is common community cookbook):
  
  ```
  E, [2014-11-14T11:51:42.834929 #5176] ERROR -- : Erb template templates/default/a2disconf.erb has a syntax error:
  E, [2014-11-14T11:51:42.834929 #5176] ERROR -- : 'erubis' is not recognized as an internal or external command,
  E, [2014-11-14T11:51:42.834929 #5176] ERROR -- : operable program or batch file.
  E, [2014-11-14T11:51:42.850529 #5176] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid template files in cookbook: apache2 (2.0.0).
  ```
- Final output is: `There was an error connecting to the Chef Server`

**Despite these errors, I can successfully run `berks vendor .\vendor` then upload all with `knife cookbook upload -a -o .\vendor`**
### Versions

ChefDK: 0.2.2 (windows)
Berkshelf: 3.1.5 (embedded in ChefDK)
### Truncated stacktrace

``` text
I, [2014-11-14T11:51:34.616487 #5176]  INFO -- : Checking if lockfile is trusted
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- : Checking backup (>= 0.0.0)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :   Checking transitive dependencies for backup (0.2.1)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :     Checking build-essential (>= 0.0.0)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :     Checking transitive dependencies for build-essential (1.4.4)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :       Already checked - skipping
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :     Checking cron (>= 0.0.0)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :     Checking transitive dependencies for cron (1.2.8)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :       Already checked - skipping
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- : Checking bamboo (>= 0.0.0)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- : Using 'chefignore' at 'C:/Users/cstewart/Documents/bamboo-cookbook/chefignore'
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :   Detected there is a cached cookbook
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :   Checking transitive dependencies for my-bamboo (0.1.0)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :     Checking bamboo (= 1.2.9)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :     Checking transitive dependencies for bamboo (1.2.9)
D, [2014-11-14T11:51:34.616487 #5176] DEBUG -- :       Already checked - skipping
D, [2014-11-14T11:51:34.756884 #5176] DEBUG -- : Using 'chefignore' at 'C:/Users/cstewart/.berkshelf/cookbooks/bamboo-1.2.9/chefignore'
D, [2014-11-14T11:51:34.850482 #5176] DEBUG -- : Using 'chefignore' at 'C:/Users/cstewart/bamboo-cookbook/chefignore'
D, [2014-11-14T11:51:34.866082 #5176] DEBUG -- : Using 'chefignore' at 'C:/Users/cstewart/.berkshelf/cookbooks/mysql_connector-0.7.2/chefignore'
I, [2014-11-14T11:51:35.006479 #5176]  INFO -- : Uploading cookbooks
D, [2014-11-14T11:51:35.006479 #5176] DEBUG -- :   No names given, using all cookbooks
I, [2014-11-14T11:51:35.037679 #5176]  INFO -- : Starting upload
D, [2014-11-14T11:51:35.131277 #5176] DEBUG -- :   Uploading apache2 (2.0.0) 'C:/Users/cstewart/.berkshelf/cookbooks/apache2-2.0.0'
D, [2014-11-14T11:51:35.224875 #5176] DEBUG -- : ==> performing authenticated Chef request as 'admin'
D, [2014-11-14T11:51:35.224875 #5176] DEBUG -- : request env: #<struct Faraday::Env method=:get, body=nil, url=#<Addressable::URI:0x1cfce48 URI:https://ec2-XXX-XXX.compute.amazonaws.com:443/cookbooks/apache2/2.0.0>, request=#<Faraday::RequestOptions proxy=#<Faraday::ProxyOptions uri=#<URI::HTTP:0x3525bd0 URL:http://xxx.xxx.xxx>>>, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v4.0.0", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"admin", "X-OPS-TIMESTAMP"=>"2014-11-14T16:51:35Z", "X-OPS-CONTENT-HASH"=>"2jmj7l5rSw0yVb/vlWAYkK/YBwk=", "X-OPS-AUTHORIZATION-1"=>"jN2p9lt+mLIDtG9xFU82EJJlbBtgmoXPOpv6lED59Jt/17d7uAUjf3iU0Y6G", "X-OPS-AUTHORIZATION-2"=>"XIS3Pi9jgi2sFzr/OvnxBBRzv6WKOZoYGtpCX78PBpJ+TWarsHD6n5HmKUm8", "X-OPS-AUTHORIZATION-3"=>"0croiMX3xnuDz737ALf3TjFnCjEhjmwgZDYnO7a1/r49wGOk9pwKs26OMt6O", "X-OPS-AUTHORIZATION-4"=>"Rit+EAw6WZGhoeSqNIvnS1apQDeZV43g4svNFZEckDijxaVH46s2M3cU5CvD", "X-OPS-AUTHORIZATION-5"=>"3wZ3P7MbRvuUipYsW1wBhhaNvYfz1fVrilHrwDGIdkYAylOJ11b69G7tFaoz", "X-OPS-AUTHORIZATION-6"=>"dmhKVTgPIL+xFpDPzFhPDnSwdt4/uzNwLSwt1wVUJw==", "HOST"=>"ec2-XXX-XXX.compute.amazonaws.com:443"}, ssl=#<Faraday::SSLOptions verify=true>, parallel_manager=nil, params=nil, response=nil, response_headers=nil, status=nil>
D, [2014-11-14T11:51:36.129658 #5176] DEBUG -- : ==> handling Chef response
D, [2014-11-14T11:51:36.129658 #5176] DEBUG -- : request env: #<struct Faraday::Env method=:get, body="{\"error\":[\"Cannot find a cookbook named apache2 with version 2.0.0\"]}", url=#<Addressable::URI:0x1cfce48 URI:https://ec2-XXX-XXX.compute.amazonaws.com:443/cookbooks/apache2/2.0.0>, request=#<Faraday::RequestOptions proxy=#<Faraday::ProxyOptions uri=#<URI::HTTP:0x3525bd0 URL:http://xxx.xxx.xxx>>>, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v4.0.0", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"admin", "X-OPS-TIMESTAMP"=>"2014-11-14T16:51:35Z", "X-OPS-CONTENT-HASH"=>"2jmj7l5rSw0yVb/vlWAYkK/YBwk=", "X-OPS-AUTHORIZATION-1"=>"jN2p9lt+mLIDtG9xFU82EJJlbBtgmoXPOpv6lED59Jt/17d7uAUjf3iU0Y6G", "X-OPS-AUTHORIZATION-2"=>"XIS3Pi9jgi2sFzr/OvnxBBRzv6WKOZoYGtpCX78PBpJ+TWarsHD6n5HmKUm8", "X-OPS-AUTHORIZATION-3"=>"0croiMX3xnuDz737ALf3TjFnCjEhjmwgZDYnO7a1/r49wGOk9pwKs26OMt6O", "X-OPS-AUTHORIZATION-4"=>"Rit+EAw6WZGhoeSqNIvnS1apQDeZV43g4svNFZEckDijxaVH46s2M3cU5CvD", "X-OPS-AUTHORIZATION-5"=>"3wZ3P7MbRvuUipYsW1wBhhaNvYfz1fVrilHrwDGIdkYAylOJ11b69G7tFaoz", "X-OPS-AUTHORIZATION-6"=>"dmhKVTgPIL+xFpDPzFhPDnSwdt4/uzNwLSwt1wVUJw==", "HOST"=>"ec2-XXX-XXX.compute.amazonaws.com:443"}, ssl=#<Faraday::SSLOptions verify=true>, parallel_manager=nil, params=nil, response=nil, response_headers={"server"=>"nginx/1.4.4", "date"=>"Fri, 14 Nov 2014 16:51:36 GMT", "content-length"=>"69", "connection"=>"keep-alive", "x-ops-api-info"=>"flavor=osc;version=11.0.2;erchef=1.4.1"}, status=404>
D, [2014-11-14T11:51:36.129658 #5176] DEBUG -- : ** error encounted in Chef response
E, [2014-11-14T11:51:42.834929 #5176] ERROR -- : Erb template templates/default/a2disconf.erb has a syntax error:
E, [2014-11-14T11:51:42.834929 #5176] ERROR -- : 'erubis' is not recognized as an internal or external command,
E, [2014-11-14T11:51:42.834929 #5176] ERROR -- : operable program or batch file.
E, [2014-11-14T11:51:42.850529 #5176] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid template files in cookbook: apache2 (2.0.0).
E, [2014-11-14T11:51:42.850529 #5176] ERROR -- : C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook.rb:201:in `validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.0.0/lib/ridley/resources/cookbook_resource.rb:197:in `upload'
...
...
C:/opscode/chefdk/bin/berks:37:in `load'
C:/opscode/chefdk/bin/berks:37:in `<main>'
There was an error connecting to the Chef Server
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf.rb:160:in `rescue in ridley_connection'
...
...
        C:/opscode/chefdk/bin/berks:37:in `load'
        C:/opscode/chefdk/bin/berks:37:in `<main>'
```

**Comment by thommay** [comment]
This looks a lot like a site problem, rather than a problem in berkshelf (it's also two years old), so I'm going to close this out. Please feel free to let us know if you're still seeing this problem.
