### ISSUE TITLE
berks stops working after bundle install (ChefDK)

### ISSUE THREAD

**Issue by mrmarbury** [berkshelf/berkshelf#1357]
Hi,

on my workstation I have the default chef workstation installation and ChefDK. Everything works fine and I can create cookbooks with "berks" until I use "bundle install" in one cookbook for the first time. After that I can use "berks" in the "bundle exec" contect only and only within a path that contains a Gemfile. If I use "berks" without "bundle exec", I get the following error:

```
`/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2087:in check_version_conflict': can't activate json-1.7.7, already activated json-1.8.1 (Gem::LoadError)`

And the stack trace:
`
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1278:in 
'activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:90:in 'block in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:89:in 'each'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:89:in 'require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.1/lib/berkshelf.rb:5:in '<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:inrequire'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.1/lib/berkshelf/cli.rb:1:in
'<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.1/bin/berks:3:in '<top (required)>'
        from /opt/chefdk/embedded/bin/berks:23:in 'load'
        from /opt/chefdk/embedded/bin/berks:23:in '<main>'
```

This also means I can only create new cookbooks with "berks" when I am in the base directory of a perviously created cookbook.

Did I miss something here?

Thx for your help,
Stefan

**Comment by jaimealsilva** [comment]
I am a completely newbie to chef and ruby so please be patient.

Just bumped into this problem while trying to run 'kitchen test' from a book example. What I get is:

```
jaime@jaime-Y40-70:~/chef-repo/cookbooks/my_test$ kitchen test
-----> Starting Kitchen (v1.2.1)
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (can't activate json-1.7.7, already activated json-1.8.1)
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
I have added 'gem "hashie", "~> 2.0"' to the cookbook Gemfile and also ran gem install hashie -v '~> 2.0' on HOME but the problem persists. This is the Gemfile:

```
jaime@jaime-Y40-70:~/chef-repo/cookbooks/my_test$ cat Gemfile
source 'https://rubygems.org'

gem 'berkshelf'

# Uncomment these lines if you want to live on the Edge:
#
# group :development do
#   gem "berkshelf", github: "berkshelf/berkshelf"
#   gem "vagrant", github: "mitchellh/vagrant", tag: "v1.6.3"
# end
#
# group :plugins do
#   gem "vagrant-berkshelf", github: "berkshelf/vagrant-berkshelf"
#   gem "vagrant-omnibus", github: "schisamo/vagrant-omnibus"
# end

gem 'test-kitchen'
gem 'kitchen-vagrant'
gem "hashie", "~> 2.0"
```

And here's what I got when run 'bundle install' in the cookbook:

```
jaime@jaime-Y40-70:~/chef-repo/cookbooks/my_test$ bundle install
Resolving dependencies...
Using addressable 2.3.6
Using multipart-post 2.0.0
Using faraday 0.9.1
Using berkshelf-api-client 1.2.0
Using buff-extensions 1.0.0
Using hashie 2.1.2
Using varia_model 0.4.0
Using buff-config 1.0.1
Using buff-ruby_engine 0.1.0
Using buff-shell_out 0.2.0
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using nio4r 1.0.1
Using celluloid-io 0.16.1
Using cleanroom 1.0.0
Using minitar 0.5.4
Using sawyer 0.6.0
Using octokit 3.7.0
Using retryable 1.3.6
Using buff-ignore 1.1.1
Using erubis 2.7.0
Using json 1.8.1
Using mixlib-log 1.6.0
Using mixlib-authentication 1.3.0
Using net-http-persistent 2.9.4
Using semverse 1.2.1
Using ridley 4.1.1
Using dep-selector-libgecode 1.0.2
Using ffi 1.9.6
Using dep_selector 1.0.3
Using solve 1.2.1
Using thor 0.19.1
Using berkshelf 3.2.2
Using mixlib-shellout 1.6.1
Using net-ssh 2.9.1
Using net-scp 1.2.1
Using safe_yaml 1.0.4
Using test-kitchen 1.2.1
Using kitchen-vagrant 0.15.0
Using bundler 1.7.5
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```
I'm running on Kubuntu 14.10, chefdk deb version is 0.3.5-1.

Thanks in advance for any help, I'm stuck here.

**Comment by blakewhite** [comment]
It sounds like you are having my issue as well. Until they can get the fixes Seth and Daniel are looking at, or everyone moves on to the newer json gem, you will need to do `bundle exec kitchen ...` instead of just `kitchen ...` and make sure your Gemfile has that hashie version on it. Hope that helps!

**Comment by jaimealsilva** [comment]
Well it seems to work that way. Now I bumped into another error but it doesn't seems to be related.

Thanks a lot!.

```
jaime@jaime-Y40-70:~/chef-repo/cookbooks/my_test$ bundle exec kitchen test 
-----> Starting Kitchen (v1.2.1)
-----> Cleaning up any prior instances of <default-ubuntu-1404>
-----> Destroying <default-ubuntu-1404>...                                             
       Finished destroying <default-ubuntu-1404> (0m0.00s).                            
-----> Testing <default-ubuntu-1404>                                                   
-----> Creating <default-ubuntu-1404>...                                               
       Bringing machine 'default' up with 'virtualbox' provider...                     
       The following berks command failed to execute:                                  
                                                                                       
           /home/jaime/.chefdk/gem/ruby/2.1.0/bin/berks --version --format json        
                                                                                       
       The stdout and stderr are shown below:                                          
                                                                                       
           stdout:                                                                     
           stderr: /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'berkshelf' (>= 0) among 56 total gem(s) (Gem::LoadError)                                                                                  
       Checked in 'GEM_PATH=/home/jaime/.vagrant.d/gems:/opt/vagrant/bin/../embedded/gems', execute `gem env` for more information                                            
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:322:in `to_spec'                                                                            
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'                                                                        
        from /home/jaime/.chefdk/gem/ruby/2.1.0/bin/berks:22:in `<main>'               
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
STDERR: The following berks command failed to execute:

    /home/jaime/.chefdk/gem/ruby/2.1.0/bin/berks --version --format json

The stdout and stderr are shown below:

    stdout: 
    stderr: /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'berkshelf' (>= 0) among 56 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/jaime/.vagrant.d/gems:/opt/vagrant/bin/../embedded/gems', execute `gem env` for more information
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:322:in `to_spec'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'
        from /home/jaime/.chefdk/gem/ruby/2.1.0/bin/berks:22:in `<main>'
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by tknerr** [comment]
@jaimealsilva that's the one I had in test-kitchen/test-kitchen#575 and is fixed by:

1. updating to vagrant-berkshelf 4.0.2 (which includes berkshelf/vagrant-berkshelf#248)
2. updating to latest kitchen-vagrant from master (which includes test-kitchen/kitchen-vagrant#126) -- v0.16.0 is not released yet so you will have to use a git ref in your Gemfile

**Comment by jaimealsilva** [comment]
Just removed chefdk and vagrant, deleted all gem dirs, and reinstalled as explained on https://github.com/berkshelf/vagrant-berkshelf/issues/212#issuecomment-53824984 and 'bundle exec kitchen test' is working now.

Thanks a lot!

**Comment by mrmarbury** [comment]
Hi,

sorry for the delay. For me the problem is solved after correcting $PATH. Should I leave this ticket open since others have similar Problems?

Cheers and Thanks,
Stefan

**Comment by nebffa** [comment]
I had my PATH incorrectly set to have `/opt/chefdk/embedded/bin` at the front instead of `/opt/chefdk/bin`. Now it's fixed!

**Comment by markl17** [comment]
why after installing berkshelf i get the following
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/c
onfig/ruby.rb:30:in `rescue in initialize': uninitialized constant Buff::Config:
:Ruby::Evaluator::Excon (Buff::Errors::InvalidConfig)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0
.1/lib/buff/config/ruby.rb:25:in `initialize'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0
.1/lib/buff/config/ruby.rb:17:in `new'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0
.1/lib/buff/config/ruby.rb:17:in `parse'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0
.1/lib/buff/config/ruby.rb:119:in `from_ruby'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0

**Comment by bpoweski** [comment]
I had a similar issue but the culprit was running the bundler zsh plugin.

**Comment by raghu-shukla** [comment]
This can be solved out by removing any of exisiting Berks* file in you working directory and adding use_sudo: false in .kitchen.yml

**Comment by lamont-granquist** [comment]
this is a very old ticket and seems to be a compendium of different gem version pinning issues and there doesn't seem to be anything actionable to fix in berkshelf.

related issues should probably be taken to the slack channel and/or stackoverflow until someone comes up with an actionable bug.
