### ISSUE TITLE
SLv3 read server certificate B: certificate verify failed (Faraday::SSLError)

### ISSUE THREAD

**Issue by jan0sch** [berkshelf/berkshelf#1360]
Hi,

I'm trying to get berkshelf running on a FreeBSD 10.1 box using Ruby 2.1 but whenever I run `berks install` I get the following error:

```
Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
/usr/local/lib/ruby/2.1/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /usr/local/lib/ruby/2.1/net/http.rb:920:in `block in connect'
	from /usr/local/lib/ruby/2.1/timeout.rb:91:in `block in timeout'
	from /usr/local/lib/ruby/2.1/timeout.rb:101:in `call'
	from /usr/local/lib/ruby/2.1/timeout.rb:101:in `timeout'
	from /usr/local/lib/ruby/2.1/net/http.rb:920:in `connect'
	from /usr/local/lib/ruby/2.1/net/http.rb:863:in `do_start'
	from /usr/local/lib/ruby/2.1/net/http.rb:852:in `start'
	from /usr/local/lib/ruby/2.1/net/http.rb:1369:in `request'
	from /usr/local/lib/ruby/2.1/net/http.rb:1128:in `get'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/request/retry.rb:87:in `call'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
	from /usr/local/lib/ruby/gems/2.1/gems/berkshelf-api-client-1.2.0/lib/berkshelf/api_client/connection.rb:62:in `universe'
	from /usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/source.rb:22:in `build_universe'
	from /usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/installer.rb:21:in `block (2 levels) in build_universe'
```

I tried to disable ssl verification in `~/.berkshelf/config.json` as mentioned in #1254 but that did not work. However the error message is somewhat different:

```
Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
Installing build-essential (2.1.3)
Installing aws (2.5.0)
Installing apt (2.6.1)
E, [2014-12-29T20:53:35.363858 #28948] ERROR -- : Actor crashed!
Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	/usr/local/lib/ruby/2.1/net/http.rb:920:in `connect'
	/usr/local/lib/ruby/2.1/net/http.rb:920:in `block in connect'
	/usr/local/lib/ruby/2.1/timeout.rb:76:in `timeout'
	/usr/local/lib/ruby/2.1/net/http.rb:920:in `connect'
	/usr/local/lib/ruby/2.1/net/http.rb:863:in `do_start'
	/usr/local/lib/ruby/2.1/net/http.rb:852:in `start'
	/usr/local/lib/ruby/2.1/net/http.rb:1369:in `request'
	/usr/local/lib/ruby/2.1/net/http.rb:1128:in `get'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/request/retry.rb:87:in `call'
	/usr/local/lib/ruby/gems/2.1/gems/ridley-4.1.1/lib/ridley/middleware/follow_redirects.rb:67:in `perform_with_redirection'
	/usr/local/lib/ruby/gems/2.1/gems/ridley-4.1.1/lib/ridley/middleware/follow_redirects.rb:60:in `call'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
	/usr/local/lib/ruby/gems/2.1/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
	/usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/community_rest.rb:119:in `find'
	/usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/community_rest.rb:103:in `download'
	/usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/downloader.rb:62:in `try_download'
	/usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/downloader.rb:36:in `block in download'
	/usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/downloader.rb:35:in `each'
	/usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/downloader.rb:35:in `download'
	/usr/local/lib/ruby/gems/2.1/gems/berkshelf-3.2.2/lib/berkshelf/installer.rb:105:in `install'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

The "Actor crashed" message repeats 3-4 times.

Is there some way to make this work? I also tried to fiddle with a custom cacert like mentioned at https://gist.github.com/fnichol/867550#the-manual-way-boring but that didn't work out either.

Regards.

**Comment by jan0sch** [comment]
I was able to workaround the issue by setting the `SSL_CERT_FILE` environment variable.

```
% export SSL_CERT_FILE=/usr/local/etc/ssl/cert.pem
% berks install
... works :-)
```

**Comment by pburkholder** [comment]
You can add this to your Berksfile (works for me)

    ENV['SSL_CERT_FILE'] = '/some/path/to/cacert.pem'

**Comment by jan0sch** [comment]
@pburkholder I'm sticking with the environment variable because we have many different developer systems and the workaround is only needed for some of them. But thanks for the hint.

**Comment by pburkholder** [comment]
@jan0sch Sure. I dropped the hint in here since it's the mostly like landing place for those seeking help w/ the issue. It would be good to get this in the Berkshelf docs.

**Comment by afiune** [comment]
if you are using `chefdk` the solution is to add the cert (supermarket or berks api) to the file `/opt/chefdk/embedded/ssl/certs/cacert.pem` 

Good luck guys! :smile:

**Comment by beeisabelm** [comment]
I tried all those solutions with .pem and berks config but none of them worked on my Windows workstation. @sethvargo's suggestion above worked. This seems to be caused by one of the Chef  core package update on our enterprise Chef server. 
1. update gem
2. update bundle

**Comment by pburkholder** [comment]
@beeisabelm What ChefDK are you using? You may have hit: https://github.com/berkshelf/berkshelf-api-client/pull/11 https://github.com/berkshelf/berkshelf-api-client/issues/9#issuecomment-136767295

**Comment by beeisabelm** [comment]
@pburkholder yes, thank you for the reference. I'll try the fix. Maybe something was still not working and I just haven't find out yet. :smile_cat:
