### ISSUE TITLE
Error executing command berks upload

### ISSUE THREAD

**Issue by Thermatix** [berkshelf/berkshelf#1375]
berks upload keeps failing with the following message:

C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-authentication-1.3.0/lib/mixlib/authentication/signedheaderauth.rb:94:in `private_encrypt': data too large for key size (OpenSSL::PKey::RSAError)

**Comment by reset** [comment]
@Thermatix are you attempting to upload a cookbook with large files in it?

**Comment by Thermatix** [comment]
To be honest, I don't know what the contents of the cookbooks are, I was trying to get a GO build agent running on aws that's deployable via chef cookbooks; the problem was specifically encountered when trying to run a build, part of which is to publish the builds cookbook to the main chef server. 

We managed to fix the problem by sidestepping it entirely, by disabling SSL verify in the berkshelf config.json. I realise this doesn't fix the problem but having it run via ssl isn't so important as we all our infrastructure over a corporate VPN.

**Comment by Enalmada** [comment]
I just moved over to a new windows 8.1 machine, installed chefdk, tried to upload my cookbooks and got this same error.  I tried it on a bunch of cookbooks that I don't think have large files...seems like it happens regardless.  Works fine on my old Windows 7 machine with manually installed berkshef (ie not chefdk).    I copied over the same chef directory, keys, etc.  Anything else I can provide that might help identify the problem? 

```
...
I, [2015-02-04T00:13:15.130961 #5828]  INFO -- : Uploading cookbooks
D, [2015-02-04T00:13:15.131961 #5828] DEBUG -- :   Names given (mentormyself-bas
e)
I, [2015-02-04T00:13:15.131961 #5828]  INFO -- : Starting upload
D, [2015-02-04T00:13:15.189966 #5828] DEBUG -- :   Uploading mentormyself-base (
0.1.12) 'c:/Users/Adam/code/chef-repo/cookbooks/mentormyself-base'
D, [2015-02-04T00:13:15.190966 #5828] DEBUG -- : Using 'chefignore' at 'c:/Users
/Adam/code/chef-repo/cookbooks/mentormyself-base/chefignore'
c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/mixlib-authentication-1.3.0/
lib/mixlib/authentication/signedheaderauth.rb:94:in `private_encrypt': data too
large for key size (OpenSSL::PKey::RSAError)
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/mixlib-authenti
cation-1.3.0/lib/mixlib/authentication/signedheaderauth.rb:94:in `sign'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/middleware/chef_auth.rb:22:in `authentication_headers'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/middleware/chef_auth.rb:66:in `call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/l
ib/faraday/request/retry.rb:110:in `call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/l
ib/faraday/rack_builder.rb:139:in `build_response'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/l
ib/faraday/connection.rb:377:in `run_request'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/connection.rb:106:in `run_request'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/l
ib/faraday/connection.rb:140:in `get'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:26:in `public_send'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:26:in `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:63:in `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/cell.rb:60:in `block in invoke'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/cell.rb:71:in `block in task'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/actor.rb:357:in `block in task'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/tasks.rb:57:in `block in initialize'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/internal_pool.rb:130:in `call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/internal_pool.rb:130:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:92:in `value'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/pool_manager.rb:41:in `_send_'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/pool_manager.rb:140:in `method_missing'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:26:in `public_send'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:26:in `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:63:in `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/cell.rb:60:in `block in invoke'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/cell.rb:71:in `block in task'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/actor.rb:357:in `block in task'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/tasks.rb:57:in `block in initialize'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:92:in `value'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/resource.rb:132:in `raw_request'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/resource.rb:123:in `request'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/resources/cookbook_resource.rb:96:in `find'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/resources/cookbook_resource.rb:190:in `upload'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:26:in `public_send'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:26:in `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:63:in `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/cell.rb:60:in `block in invoke'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/cell.rb:71:in `block in task'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/actor.rb:357:in `block in task'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/tasks.rb:57:in `block in initialize'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/internal_pool.rb:130:in `call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/internal_pool.rb:130:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/calls.rb:92:in `value'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.
0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb
:55:in `block (2 levels) in upload'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb
:51:in `each'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb
:51:in `block in upload'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley/client.rb:38:in `open'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/li
b/ridley.rb:51:in `open'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf.rb:144:in `
ridley_connection'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb
:50:in `upload'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb
:37:in `run'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.r
b:545:in `upload'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:208:
in `upload'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib
/thor/command.rb:27:in `run'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib
/thor/invocation.rb:126:in `invoke_command'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib
/thor.rb:359:in `dispatch'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:i
n `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib
/thor/base.rb:440:in `start'
        from c:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:i
n `execute!'
        from c:/opscode/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (req
uired)>'
        from c:/opscode/chefdk/bin/berks:43:in `load'
        from c:/opscode/chefdk/bin/berks:43:in `<main>'
```

**Comment by smith** [comment]
It can also happen if there is not a node name set.

**Comment by lamont-granquist** [comment]
this probably needs to get opened as a new issue against berkshelf 7.0 if it still exists.  it definitely needs a better repro case and more information about the failure (full stack trace using `-d`, etc).
