### ISSUE TITLE
Assuming cookbook folder as the same name of the cookbook against berks-api with filestore

### ISSUE THREAD

**Issue by gionn** [berkshelf/berkshelf#1422]
I am using berks-api with the following config:

```
{
  "endpoints": [
    {
      "type": "file_store",
      "options": {
        "path": "/var/lib/jenkins/workspace"
      }
    }
  ]
}
```

In the workspace folder I have multiple cookbooks, each one with the main folder name cookbook-(cookbook-name).

Berks update fail with:

```
E, [2015-04-29T13:41:56.771738 #8798] ERROR -- : Actor crashed!
RuntimeError: unknown file type: /tmp/d20150429-8798-1rcrynx/cd-appdeploy
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1396:in `copy'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1506:in `call'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1506:in `wrap_traverse'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:441:in `block in cp_r'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
        /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/core_ext/file_utils.rb:11:in `mv'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:66:in `import'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:30:in `import'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:106:in `block in install'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:38:in `block in download'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `each'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `download'
        /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:105:in `install'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

/tmp/d20150429-8798-1rcrynx/cd-appdeploy doesn't exists, while /tmp/d20150429-8798-1rcrynx/cookbook-cd-appdeploy does exists.

**Comment by gionn** [comment]
Indeed a workaround is to rename folder with the same name of the 'name' specified in metadata.rb

**Comment by thommay** [comment]
Hi,
if this is still a problem, please feel free to reopen this bug, but I'm going to close it for now since I'm reasonably certain this was a bug that was fixed.
