### ISSUE TITLE
Add support for zip archives from community site

### ISSUE THREAD

**Issue by patcon** [berkshelf/berkshelf#1432]
I was getting odd errors during `berks install`:

```
Using postfix (3.6.2)
Using sudo (2.7.1)
Using timezone-ii (0.2.0)
Using ulimit (0.3.3)
E, [2015-06-07T22:29:34.058333 #1363] ERROR -- : Actor crashed!
Berkshelf::UnknownCompressionType: The file at '/tmp/community-rest-stream20150607-1363-12qkmsj' is not a known compression type
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:19:in `unpack'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:105:in `download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:62:in `try_download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:36:in `block in download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `each'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:105:in `install'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    (celluloid):0:in `remote procedure call'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
The file at '/tmp/community-rest-stream20150607-1363-12qkmsj' is not a known compression type
```

I thought it was with the `ulimit` cookbook, and so spent some time looking into the wrong problem. Turns out that it was silently failing on the _next_ community cookbook, which was [`selfsigned_certificate`](https://supermarket.chef.io/cookbooks/selfsigned_certificate). Seems it stores its archive as a zip, that is perhaps not supported ([only gzip and tar?](https://github.com/berkshelf/berkshelf/blob/13c595c69266be78870417bdf3ec92efab4ea60e/lib/berkshelf/community_rest.rb#L13-L20)). Pulling directly from github eventually solved this for me.

Anyhow, perhaps we could add better error handling, mentioning the more useful "destination" directory rather than the "target", a temporary file with a hashed name?

**Comment by patcon** [comment]
Related:
- https://github.com/berkshelf/berkshelf/pull/839
- https://github.com/berkshelf/berkshelf/issues/1292

**Comment by thommay** [comment]
Pretty sure this is long since fixed; if that's not the case please feel free to reopen this issue.
