### ISSUE TITLE
berks package results in Archive::Tar::Minitar::FileNameTooLong error

### ISSUE THREAD

**Issue by bqumsiyeh** [berkshelf/berkshelf#1437]
When doing a `berks package`, I run into the following error:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:446:in `split_name': Archive::Tar::Minitar::FileNameTooLong (Archive::Tar::Minitar::FileNameTooLong)
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:335:in `add_file_simple'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:920:in `pack_file'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:960:in `block (2 levels) in pack'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/find.rb:48:in `block (2 levels) in find'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/find.rb:47:in `catch'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/find.rb:47:in `block in find'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/find.rb:42:in `each'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/find.rb:42:in `find'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:959:in `block in pack'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:802:in `open'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:948:in `pack'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/packager.rb:45:in `block in run'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/packager.rb:43:in `chdir'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/packager.rb:43:in `run'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:565:in `block in package'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:563:in `package'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:367:in `package'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
    from /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
    from /usr/bin/berks:43:in `load'
    from /usr/bin/berks:43:in `<main>'
```

The tarball gets created but the contents of it are incomplete.  The name of the file is `cookbooks-1434591893.tar.gz`.  As far as I can tell, the `FileNameTooLong` error should only get thrown if the file name is greater than 256 bytes, and my tarball name is nowhere near that size.

Anyone have an ideas or suggestions?  Much appreciated.

**Comment by thommay** [comment]
We no longer use the minitar gem, so this should no longer be an issue. Thanks for submitting, and I'm sorry you didn't get a response faster!
