### ISSUE TITLE
ERROR -- : Actor crashed! during berks install

### ISSUE THREAD

**Issue by ianbamforth** [berkshelf/berkshelf#1449]
Berksfile:

    source "https://supermarket.chef.io"
    
    metadata
    
    cookbook 'postgresql'
    cookbook 'database'

metadata.rb:

    depends "postgresql"
    depends "database"

Resolving cookbook dependencies...
Fetching 'tracsis_enterprise_postgres' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Using tracsis_enterprise_postgres (0.1.0) from source at .
Installing database (4.0.8)
Installing postgresql (3.4.20)
Using apt (2.7.0)
Using build-essential (2.2.3)
Using openssl (4.0.0)
Using chef-sugar (3.1.1)

E, [2015-08-13T11:14:17.247685 #17081] ERROR -- : Actor crashed!
Errno::ETIMEDOUT: Connection timed out - connect(2) for "app-supermarket-prod-i-c663c400.opscode.us" port 443
        /home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
        /home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `open'
        /home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
        /home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:74:in `timeout'

**Comment by ianbamforth** [comment]
Looks like a service outage:
http://status.chef.io/post/126582200891/supermarket-berkshelf-failures-ongoing

May as well close this
