### ISSUE TITLE
berks crash parsing attributes in metadata.rb

### ISSUE THREAD

**Issue by adrianbn** [berkshelf/berkshelf#1461]
Hi,

I'm using berkshelf 3.3.0 (also verified in 2.2.4) and it crashes when the metadata.rb file contains attribute declarations. I'm not 100% sure if this issue falls squarely in Berkshelf's corner or in Ridley's, but any help would be much appreciated. 

Here is the stacktrace:
```
$  berks -d
An error occurred while reading the Berksfile:

  Could not parse `metadata.rb': uninitialized constant Ridley::Mixin::ParamsValidate::ValidationFailed
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/params_validate.rb:121:in `_pv_equal_to'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/params_validate.rb:64:in `block (2 levels) in validate'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/params_validate.rb:61:in `each'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/params_validate.rb:61:in `block in validate'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/params_validate.rb:51:in `each'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/params_validate.rb:51:in `validate'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/chef/cookbook/metadata.rb:381:in `attribute'
  role_base_psec/metadata.rb:44:in `block in from_file'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/from_file.rb:31:in `instance_eval'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/from_file.rb:31:in `block in from_file'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/from_file.rb:74:in `with_error_handling'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/from_file.rb:30:in `from_file'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/ridley-4.2.0/lib/ridley/mixin/from_file.rb:5:in `from_file'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/berkshelf-3.3.0/lib/berkshelf/berksfile.rb:164:in `metadata'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `public_send'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `block (3 levels) in cleanroom'
  role_base_psec/Berksfile:3:in `evaluate'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `instance_eval'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `evaluate'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/cleanroom-1.0.0/lib/cleanroom.rb:56:in `evaluate_file'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/cleanroom-1.0.0/lib/cleanroom.rb:173:in `evaluate_file'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/berkshelf-3.3.0/lib/berkshelf/berksfile.rb:23:in `from_file'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/berkshelf-3.3.0/lib/berkshelf/berksfile.rb:12:in `from_options'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:142:in `install'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:52:in `dispatch'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:27:in `execute!'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/gems/berkshelf-3.3.0/bin/berks:5:in `<top (required)>'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/bin/berks:23:in `load'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/bin/berks:23:in `<main>'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/bin/ruby_executable_hooks:15:in `eval'
  .rvm/gems/ruby-2.0.0-p643@berkshelf/bin/ruby_executable_hooks:15:in `<main>'
```

If I comment out the attribute definitions in the metadata.rb file it works.

**Comment by reset** [comment]
@adrianbn thanks for the heads up. This change to Ridley should fix the issue https://github.com/reset/ridley/pull/316. It'll be in the next release of Berkshelf.

**Comment by adrianbn** [comment]
Thanks!
