### ISSUE TITLE
berks doesn't work when chef-server is using a custom port

### ISSUE THREAD

**Issue by chr4** [berkshelf/berkshelf#1463]
When I configure a custom port for `chef_server_url` in my `.chef/knife.rb`, `berks upload` fails with the following message:

```
$ berks upload --ssl-verify=false
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each': task was terminated (Celluloid::Task::TerminatedError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:51:in `each'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:51:in `block in upload'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/client.rb:38:in `open'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley.rb:51:in `open'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf.rb:144:in `ridley_connection'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:50:in `upload'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:37:in `run'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:545:in `upload'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:208:in `upload'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
        from /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
        from /opt/chefdk/bin/berks:44:in `load'
        from /opt/chefdk/bin/berks:44:in `<main>'
```

The relevant section in `knife.rb`:

``` ruby
# Works
chef_server_url          'https://chef.example.com/organizations/example'

# Doesn't work
# chef_server_url          'https://chef.example.com:10443/organizations/example'
```

**Comment by chr4** [comment]
This is probably not a direct bug in Berkshelf, but in knife.

**Comment by lamont-granquist** [comment]
closing this as ridley/celluloid have been removed in berkshelf 7.0, if the problem persists, please open a fresh issue.
