### ISSUE TITLE
undefined method `chef_server_url' 

### ISSUE THREAD

**Issue by gretel** [berkshelf/berkshelf#1496]
that error leaves me clueless. been `grep` and `find`ing half day to find some cruft that might be chef related. there is no nothing related, and `berks` just fails. `berkshelf-4.0.1` fails in the samy way. any hint is appreciated!

```
/Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:80:in `<class:Config>': undefined method `chef_server_url' for #<Ridley::Chef::Config:0x007f8dbb97af90> (NoMethodError)
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:4:in `<module:Berkshelf>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:3:in `<top (required)>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:3:in `require_relative'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:3:in `<class:CookbookGenerator>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:2:in `<module:Berkshelf>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:1:in `<top (required)>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:197:in `require_relative'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:197:in `<top (required)>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:1:in `require'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:1:in `<top (required)>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/bin/berks:3:in `require'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/gems/berkshelf-3.3.0/bin/berks:3:in `<top (required)>'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/bin/berks:23:in `load'
  from /Users/somewho/whatever/kitchen/cookbooks/whatever_graphite_ng/vendor/cache/ruby/2.3.0/bin/berks:23:in `<main>'
```

**Comment by acqant** [comment]
+1
Seeing this for the first time today.  Can't even berks -v

**Comment by acqant** [comment]
dup of 
https://github.com/berkshelf/berkshelf/issues/1495

**Comment by reset** [comment]
Fixed in https://github.com/berkshelf/ridley/pull/331
