### ISSUE TITLE
Vagrant berkshelf fails to parse Berksfile when referencing local or git cookbook

### ISSUE THREAD

**Issue by chuangtim** [berkshelf/berkshelf#1539]
Environment

``` ruby
Mac OS 10.10.3
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
Vagrant 1.8.1
```

vagrant plugin list:

``` ruby
vagrant-berkshelf (4.1.0)
vagrant-cachier (1.2.1)
vagrant-omnibus (1.4.1)
vagrant-opsworks (0.3.1)
vagrant-share (1.1.5, system)
```

my Berksfile

``` ruby
source "https://supermarket.chef.io"
cookbook "mongodb", git: 'git://github.com/chef-brigade/mongodb-cookbook.git'
metadata
```

I got an errors as follows:

``` ruby
The following berks command failed to execute:

    /usr/local/bin/berks vendor /Users/zhuangtim/.berkshelf/vagrant-berkshelf/shelves/berkshelf20160330-4138-1y2ca5p-db --berksfile /Users/zhuangtim/vagrant/cookbooks/cookbook-test/Berksfile

The stdout and stderr are shown below:

    stdout: Resolving cookbook dependencies...
Fetching 'cookbook-test/' from source at .
Fetching 'mongodb' from git://github.com/chef-brigade/mongodb-cookbook.git (at master)
Fetching cookbook index from https://supermarket.chef.io...

    stderr: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `initialize': getaddrinfo: nodename nor servname provided, or not known (https://supermarket.chef.io:443) (SocketError)
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `new'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `create_socket'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:747:in `block in connect'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:101:in `call'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:612:in `query'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:164:in `query'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1191:in `do_get_block'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/httpclient.rb:36:in `call'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/request/retry.rb:116:in `call'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-api-client-2.0.0/lib/berkshelf/api_client/connection.rb:60:in `universe'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.2.0/lib/berkshelf/source.rb:22:in `build_universe'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.2.0/lib/berkshelf/installer.rb:21:in `block (2 levels) in build_universe'


It appears that you are not using the ChefDK. Please note that Vagrant Berkshelf
works best when used with the ChefDK, and other installation methods are not
officially supported.

Please download and install the latest version of the ChefDK from:

    https://downloads.chef.io/chef-dk

and follow the installation instructions. Do not forget to add the ChefDK to
your PATH.
```

help please,thank you.

**Comment by jeganila** [comment]
check whether you are behind the proxy .. if so please add 

export http_proxy=http://proxy:port/
export SSL_CERT_FILE=/c/opscode/chefdk/embedded/ssl/certs/cacert.pem
export http_proxy_user=<user>
export http_proxy_pass=<password>

**Comment by cheeseplus** [comment]
This is a socket issue and purely connectivity related, the proxy directions may help but this is ultimately not a berkshelf issue.

**Comment by lamont-granquist** [comment]
vagrant-berkshelf is pretty much deprecated in favor of test-kitchen to drive creating virts as well.  it is not on the happy path to getting support.
