### ISSUE TITLE
mixlib-archive dependency

### ISSUE THREAD

**Issue by ctbarrett** [berkshelf/berkshelf#1571]
FYI, I received the following error when attempting to run `bundle exec berks install` after updating to 4.3.4:

```bash
$ bundle exec berks install
/Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/lib/berkshelf/community_rest.rb:3:in `require': cannot load such file -- mixlib/archive (LoadError)
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/lib/berkshelf/community_rest.rb:3:in `<top (required)>'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/lib/berkshelf.rb:196:in `require_relative'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/lib/berkshelf.rb:196:in `<top (required)>'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/lib/berkshelf/cli.rb:1:in `require'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/lib/berkshelf/cli.rb:1:in `<top (required)>'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/bin/berks:3:in `require'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/gems/berkshelf-4.3.4/bin/berks:3:in `<top (required)>'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/bin/berks:22:in `load'
	from /Users/x3hr/.chefdk/gem/ruby/2.1.0/bin/berks:22:in `<main>'
```

I had berkshelf pinned at '~> 4.3.3' in my Gemfile, and updated to 4.3.4 when the CI tests for the cookbook I was working on started failing.

Looks like a dependency was introduced with 4.3.4 on 'mixlib-archive', which is not yet released:
https://github.com/berkshelf/berkshelf/blob/v4.3.4/Gemfile#L33-L34
```markdown
# until a gem release!
gem "mixlib-archive", github: "chef/mixlib-archive"
```

https://github.com/berkshelf/berkshelf/blob/v4.3.4/lib/berkshelf/downloader.rb#L2
```ruby
require 'net/http'
require 'mixlib/archive'

module Berkshelf
  class Downloader
    extend Forwardable
```

https://github.com/berkshelf/berkshelf/blob/v4.3.4/lib/berkshelf/community_rest.rb#L3
```ruby
require 'open-uri'
require 'retryable'
require 'mixlib/archive'

module Berkshelf
  class CommunityREST < Faraday::Connection
    class << self
```

I've pinned on 4.3.3 for now, but figured I'd post it here for awareness, at least, since it's not explicitly called out in the changelog.

**Comment by coderanger** [comment]
Just to echo, getting multiple reports of this on IRC and Slack.
