### ISSUE TITLE
:chef_server 404 / url error

### ISSUE THREAD

**Issue by TimCorwin** [berkshelf/berkshelf#1574]
I am seeing mostly same symptoms as #1541, but the Debug log shows a 404, not a 302:
I have reproduced on multiple chef servers and build nodes, and with both ChefDK 0.13.x and 0.15.15, and renaming the ~/.chefdk(and confirming I could no longer use the gems in it) did not change the behavior.

```
I, [2016-06-24T22:10:26.575566 #93460]  INFO -- : Reducing lockfile
D, [2016-06-24T22:10:26.575643 #93460] DEBUG -- : Current lockfile:
D, [2016-06-24T22:10:26.575656 #93460] DEBUG -- : 
D, [2016-06-24T22:10:26.575690 #93460] DEBUG -- :   DEPENDENCIES
D, [2016-06-24T22:10:26.575700 #93460] DEBUG -- :   
D, [2016-06-24T22:10:26.575708 #93460] DEBUG -- :   GRAPH
D, [2016-06-24T22:10:26.575716 #93460] DEBUG -- : 
D, [2016-06-24T22:10:26.575723 #93460] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2016-06-24T22:10:26.575731 #93460] DEBUG -- : Removing transitive dependencies
D, [2016-06-24T22:10:26.575785 #93460] DEBUG -- :   Checking bms_ea (>= 0.0.0)
D, [2016-06-24T22:10:26.575802 #93460] DEBUG -- :     Skipping (not graphed)
D, [2016-06-24T22:10:26.575814 #93460] DEBUG -- : New lockfile:
D, [2016-06-24T22:10:26.575821 #93460] DEBUG -- : 
D, [2016-06-24T22:10:26.575833 #93460] DEBUG -- :   DEPENDENCIES
D, [2016-06-24T22:10:26.575841 #93460] DEBUG -- :   
D, [2016-06-24T22:10:26.575848 #93460] DEBUG -- :   GRAPH
D, [2016-06-24T22:10:26.575855 #93460] DEBUG -- : 
Resolving cookbook dependencies...
I, [2016-06-24T22:10:26.575930 #93460]  INFO -- : Checking if lockfile is trusted
D, [2016-06-24T22:10:26.575950 #93460] DEBUG -- : Checking bms_ea (>= 0.0.0)
D, [2016-06-24T22:10:26.575960 #93460] DEBUG -- :   Not in lockfile - cannot be trusted!
I, [2016-06-24T22:10:26.575971 #93460]  INFO -- : Installing from universe
Fetching 'bms_ea' from source at .
D, [2016-06-24T22:10:26.576909 #93460] DEBUG -- : Using 'chefignore' at '/Users/timothycorwin/GIT/chef-repo/cookbooks/bms_ea/chefignore'
D, [2016-06-24T22:10:26.579734 #93460] DEBUG -- :   Creating a resolver
Fetching cookbook index from https://chef.svc.asv.ice.gecis.io/organizations/serviceops-asv...
Fetching cookbook index from https://supermarket.chef.io...
D, [2016-06-24T22:10:26.677652 #93460] DEBUG -- : ==> performing authenticated Chef request as 'serviceops-asv'
D, [2016-06-24T22:10:26.677748 #93460] DEBUG -- : request env: #<struct Faraday::Env method=:get, body=nil, url=#<Addressable::URI:0x3fc6710714b8 URI:https://chef.svc.asv.ice.gecis.io:443/organizations/serviceops-asv/universe>, request=#<Faraday::RequestOptions (empty)>, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v4.5.1", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"serviceops-asv", "X-OPS-TIMESTAMP"=>"2016-06-25T02:10:26Z", "X-OPS-CONTENT-HASH"=>"2jmj7l5rSw0yVb/vlWAYkK/YBwk=", "X-OPS-AUTHORIZATION-1"=>"NawUmp4HyFze5YGs+QEQ5wcweOBbKj2nme1fQ51l8vqeKlvSkSYbZs7rEQVA", "X-OPS-AUTHORIZATION-2"=>"Q3I5b0SKkcz7HKwp/o9bPK5T60YvlULQiSB0HvXH7KIe1ehuMAGb69YSk5+r", "X-OPS-AUTHORIZATION-3"=>"UY54kL0nJxca86Xhgh3aSOSiv9UHudRfpWlYLIpNpokfRxmBMimGY9nlvxvU", "X-OPS-AUTHORIZATION-4"=>"8LQdfg11wYXpVE80EIAoJdsgWFro0XNGSqIktmjAWThkSZN3x+6bntSZzFYG", "X-OPS-AUTHORIZATION-5"=>"x9orUd4J4FAOisZsoA4eIoTgccRCtMICh6xObhRhljJTsa9hrtegBGNdixdw", "X-OPS-AUTHORIZATION-6"=>"yVLLVN+sSIiL8olmQxMwh3iRsNaj6zdhn+XSWpz5vg==", "HOST"=>"chef.svc.asv.ice.gecis.io:443"}, ssl=#<Faraday::SSLOptions (empty)>, parallel_manager=nil, params=nil, response=nil, response_headers=nil, status=nil>
D, [2016-06-24T22:10:26.926214 #93460] DEBUG -- : ==> handling Chef response
D, [2016-06-24T22:10:26.926538 #93460] DEBUG -- : request env: #<struct Faraday::Env method=:get, body="<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n  <title>Chef - 404 Not Found</title>\n  <link media=\"all\" rel=\"stylesheet\" type=\"text/css\" href=\"/css/all.css\" />\n  <!--[if lt IE 7]><link rel=\"stylesheet\" type=\"text/css\" href=\"/css/lt7.css\" /><![endif]-->\n</head>\n<body>\n  <div class=\"header-block\">\n    <div id=\"header\">\n      <strong class=\"logo\"><a href=\"http://www.getchef.com\">Chef</a></strong>\n    </div>\n  </div>\n  <div id=\"wrapper\">\n    <div id=\"main\">\n      <div class=\"mybox\">\n        <div id=\"content\">\n          <h1>404 - Not Found</h1>\n          <p>Sorry, I can't find what you are looking for.</p>\n        </div>\n      </div>\n    </div>\n  </div>\n  <div class=\"footer-block\">\n    <div id=\"footer\">\n      <div class=\"mybox\">\n      </div>\n      <div class=\"footer-bottom\">\n        <span>&copy; 2010&thinsp;&ndash;&thinsp;2014 Chef Software, Inc. All Rights Reserved</span>\n      </div>\n    </div>\n  </div>\n</body>\n</html>\n", url=#<Addressable::URI:0x3fc6710714b8 URI:https://chef.svc.asv.ice.gecis.io:443/organizations/serviceops-asv/universe>, request=#<Faraday::RequestOptions (empty)>, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v4.5.1", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"serviceops-asv", "X-OPS-TIMESTAMP"=>"2016-06-25T02:10:26Z", "X-OPS-CONTENT-HASH"=>"2jmj7l5rSw0yVb/vlWAYkK/YBwk=", "X-OPS-AUTHORIZATION-1"=>"NawUmp4HyFze5YGs+QEQ5wcweOBbKj2nme1fQ51l8vqeKlvSkSYbZs7rEQVA", "X-OPS-AUTHORIZATION-2"=>"Q3I5b0SKkcz7HKwp/o9bPK5T60YvlULQiSB0HvXH7KIe1ehuMAGb69YSk5+r", "X-OPS-AUTHORIZATION-3"=>"UY54kL0nJxca86Xhgh3aSOSiv9UHudRfpWlYLIpNpokfRxmBMimGY9nlvxvU", "X-OPS-AUTHORIZATION-4"=>"8LQdfg11wYXpVE80EIAoJdsgWFro0XNGSqIktmjAWThkSZN3x+6bntSZzFYG", "X-OPS-AUTHORIZATION-5"=>"x9orUd4J4FAOisZsoA4eIoTgccRCtMICh6xObhRhljJTsa9hrtegBGNdixdw", "X-OPS-AUTHORIZATION-6"=>"yVLLVN+sSIiL8olmQxMwh3iRsNaj6zdhn+XSWpz5vg==", "HOST"=>"chef.svc.asv.ice.gecis.io:443"}, ssl=#<Faraday::SSLOptions (empty)>, parallel_manager=nil, params=nil, response=#<Faraday::Response:0x007f8ce38009b8 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n  <title>Chef - 404 Not Found</title>\n  <link media=\"all\" rel=\"stylesheet\" type=\"text/css\" href=\"/css/all.css\" />\n  <!--[if lt IE 7]><link rel=\"stylesheet\" type=\"text/css\" href=\"/css/lt7.css\" /><![endif]-->\n</head>\n<body>\n  <div class=\"header-block\">\n    <div id=\"header\">\n      <strong class=\"logo\"><a href=\"http://www.getchef.com\">Chef</a></strong>\n    </div>\n  </div>\n  <div id=\"wrapper\">\n    <div id=\"main\">\n      <div class=\"mybox\">\n        <div id=\"content\">\n          <h1>404 - Not Found</h1>\n          <p>Sorry, I can't find what you are looking for.</p>\n        </div>\n      </div>\n    </div>\n  </div>\n  <div class=\"footer-block\">\n    <div id=\"footer\">\n      <div class=\"mybox\">\n      </div>\n      <div class=\"footer-bottom\">\n        <span>&copy; 2010&thinsp;&ndash;&thinsp;2014 Chef Software, Inc. All Rights Reserved</span>\n      </div>\n    </div>\n  </div>\n</body>\n</html>\n" @url=#<Addressable::URI:0x3fc6710714b8 URI:https://chef.svc.asv.ice.gecis.io:443/organizations/serviceops-asv/universe> @request=#<Faraday::RequestOptions (empty)> @request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v4.5.1", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"serviceops-asv", "X-OPS-TIMESTAMP"=>"2016-06-25T02:10:26Z", "X-OPS-CONTENT-HASH"=>"2jmj7l5rSw0yVb/vlWAYkK/YBwk=", "X-OPS-AUTHORIZATION-1"=>"NawUmp4HyFze5YGs+QEQ5wcweOBbKj2nme1fQ51l8vqeKlvSkSYbZs7rEQVA", "X-OPS-AUTHORIZATION-2"=>"Q3I5b0SKkcz7HKwp/o9bPK5T60YvlULQiSB0HvXH7KIe1ehuMAGb69YSk5+r", "X-OPS-AUTHORIZATION-3"=>"UY54kL0nJxca86Xhgh3aSOSiv9UHudRfpWlYLIpNpokfRxmBMimGY9nlvxvU", "X-OPS-AUTHORIZATION-4"=>"8LQdfg11wYXpVE80EIAoJdsgWFro0XNGSqIktmjAWThkSZN3x+6bntSZzFYG", "X-OPS-AUTHORIZATION-5"=>"x9orUd4J4FAOisZsoA4eIoTgccRCtMICh6xObhRhljJTsa9hrtegBGNdixdw", "X-OPS-AUTHORIZATION-6"=>"yVLLVN+sSIiL8olmQxMwh3iRsNaj6zdhn+XSWpz5vg==", "HOST"=>"chef.svc.asv.ice.gecis.io:443"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x007f8ce38009b8 ...> @response_headers={"Server"=>"openresty/1.7.10.1", "Date"=>"Sat, 25 Jun 2016 02:10:26 GMT", "Content-Type"=>"text/html", "Transfer-Encoding"=>"chunked", "Connection"=>"keep-alive", "ETag"=>"W/\"55f0c58d-43f\"", "Content-Encoding"=>"gzip"} @status=404>>, response_headers={"Server"=>"openresty/1.7.10.1", "Date"=>"Sat, 25 Jun 2016 02:10:26 GMT", "Content-Type"=>"text/html", "Transfer-Encoding"=>"chunked", "Connection"=>"keep-alive", "ETag"=>"W/\"55f0c58d-43f\"", "Content-Encoding"=>"gzip"}, status=404>
D, [2016-06-24T22:10:26.926579 #93460] DEBUG -- : ** error encounted in Chef response
D, [2016-06-24T22:10:28.907921 #93460] DEBUG -- : ==> parsing Chef response body as JSON

/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-api-client-2.0.2/lib/berkshelf/api_client/chef_server_connection.rb:24:in `rescue in universe': undefined local variable or method `url' for #<Berkshelf::APIClient::ChefServerConnection:0x007f8ce41a36c8> (NameError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-api-client-2.0.2/lib/berkshelf/api_client/chef_server_connection.rb:14:in `universe'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/source.rb:43:in `build_universe'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/installer.rb:21:in `block (2 levels) in build_universe'
```

**Comment by lamont-granquist** [comment]
is this as simple as the chef-server is too old to support the universe endpoint?

**Comment by thommay** [comment]
Yep, looks like. @TimCorwin can you confirm what version of chef-server you're running?

**Comment by TimCorwin** [comment]
Yes, you are correct; I remembered wrong and our shared Chef server is 12.3.1 so of course it doesn’t work.
Sorry!

**Comment by thommay** [comment]
Closed as invalid. Thanks for the report and for confirming the behaviour is as expected.
