### ISSUE TITLE
"No live threads left. Deadlock?" error when running Chefspec (or running `chef verify` or other conditions)

### ISSUE THREAD

**Issue by tas50** [berkshelf/berkshelf#1619]
When running Chefspec without a berks install/berks update first we're getting the following error now:

```
15 files inspected, no offenses detected
/usr/local/Cellar/ruby/2.3.1/bin/ruby -I/usr/local/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib:/usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred in a `before(:suite)` hook.
Failure/Error:
  berksfile.sources.collect do |source|
    Thread.new do
      begin
        Berkshelf.formatter.msg("Fetching cookbook index from #{source.uri}...")
        source.build_universe
      rescue Berkshelf::APIClientError => ex
        Berkshelf.formatter.warn "Error retrieving universe from source: #{source}"
        Berkshelf.formatter.warn "  * [#{ex.class}] #{ex}"
      end
    end

fatal:
  No live threads left. Deadlock?
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/installer.rb:27:in `join'
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/installer.rb:27:in `map'
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/installer.rb:27:in `build_universe'
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/installer.rb:161:in `install_from_universe'
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/installer.rb:39:in `run'
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/berksfile.rb:422:in `install'
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/berksfile.rb:631:in `block in vendor'
# /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
# /usr/local/lib/ruby/gems/2.3.0/gems/berkshelf-5.1.0/lib/berkshelf/berksfile.rb:629:in `vendor'
# /usr/local/lib/ruby/gems/2.3.0/gems/chefspec-5.2.0/lib/chefspec/berkshelf.rb:39:in `block in setup!'
# /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
# /usr/local/lib/ruby/gems/2.3.0/gems/chefspec-5.2.0/lib/chefspec/berkshelf.rb:35:in `setup!'
# /usr/local/lib/ruby/gems/2.3.0/gems/chefspec-5.2.0/lib/chefspec/berkshelf.rb:61:in `block (2 levels) in <top (required)>'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/example.rb:443:in `instance_exec'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/example.rb:443:in `instance_exec'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/hooks.rb:350:in `run'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1882:in `block in run_suite_hooks'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1880:in `each'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1880:in `run_suite_hooks'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1834:in `with_suite_hooks'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:112:in `block in run_specs'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:77:in `report'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:111:in `run_specs'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:87:in `run'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
# /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/exe/rspec:4:in `<main>'
#
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 0.33109 seconds (files took 23.04 seconds to load)
0 examples, 0 failures
```

**Comment by lamont-granquist** [comment]
you could dump out the berksfile.sources array in that `#build_universe` call and see if something is weird in the input to that routine.   otherwise its really weird because it looks like you've got as many `Thread.new`s called as you will call `join` which is entirely idomatic ruby, and you're calling join on the object returned by Thread.new and it should handle the fact that the thread ended early.

about all i got is that this is some kind of chefspec-berkshelf interaction bug which causes a thread to exit quick / crash or something(?), and that is gobbled up by what looks like a threading bug in ruby 2.3, which is weird...

**Comment by jwm** [comment]
@tas50 I came across the same behavior after upgrading from ChefDK 0.19.6 to 1.0.3. After some futile troubleshooting, I went scorched earth and removed `~/.chef/` and `~/.chefdk/`. After that, `rspec` was fine.

**Comment by lamont-granquist** [comment]
It does look like blowing away all the state (~/.chefdk and /opt/chefdk and reinstalling fresh) fixes this issue.  this may boil down to these bugs:

https://github.com/chef/chef-dk/issues/871
https://github.com/chef/chef-dk/issues/530
https://github.com/chef/chef/issues/4939

**Comment by pc-mreeves** [comment]
Most of the time running berks install fixes this issue in my experience.

**Comment by irinatag** [comment]
I was getting deadlocks on berks install. uninstall & fresh reinstall fixed as per above comment.
