### ISSUE TITLE
Berkshelf::CommunitySiteError: An unexpected error occurred retrieving

### ISSUE THREAD

**Issue by eovolkov** [berkshelf/berkshelf#1620]
```
chef exec berks --version
4.3.2
evolkov-wf:chef evolkov$ chef --version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3
```
======================
Cookbook Berksfile:

```
source "https://supermarket.chef.io"
metadata
Dir.glob('../*').each do |path|
  if File.basename(Dir.pwd) != File.basename(path) && File.directory?(path)
    cookbook File.basename(path), :path => path
  end
end
```
======================
Errors:

```
18:45:56 E, [2016-10-10T18:45:56.642554 #31998] ERROR -- : Actor crashed!
18:45:56 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'application' (5.1.0) from the cookbook site at ''.
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:56 	(celluloid):0:in `remote procedure call'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:56 Using bagapp (0.1.2) from source at cookbooks/bagapp
18:45:56 Using authweb (0.1.3) from source at cookbooks/authweb
18:45:56 Installing beaver (1.6.0)
18:45:56 E, [2016-10-10T18:45:56.717638 #31998] ERROR -- : Actor crashed!
18:45:56 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'apache2' (3.2.2) from the cookbook site at ''.
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:56 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:56 Using bluepill (2.3.3) from source at cookbooks/bluepill
18:45:56 Using breeze (1.9.9) from source at cookbooks/breeze
18:45:56 Installing build-essential (3.2.0)
18:45:56 An unexpected error occurred retrieving 'ant' (1.0.3) from the cookbook site at ''.
18:45:57 E, [2016-10-10T18:45:56.737756 #31998] ERROR -- : Actor crashed!
18:45:57 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'ant' (1.0.3) from the cookbook site at ''.
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:57 E, [2016-10-10T18:45:56.774265 #31998] ERROR -- : Actor crashed!
18:45:57 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'application_git' (1.1.0) from the cookbook site at ''.
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:57 E, [2016-10-10T18:45:56.797904 #31998] ERROR -- : Actor crashed!
18:45:57 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'apt' (2.9.2) from the cookbook site at ''.
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:57 E, [2016-10-10T18:45:56.876976 #31998] ERROR -- : Actor crashed!
18:45:57 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'ark' (1.1.0) from the cookbook site at ''.
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:57 E, [2016-10-10T18:45:57.007231 #31998] ERROR -- : Actor crashed!
18:45:57 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'application_python' (4.0.0) from the cookbook site at ''.
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:57 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:58 E, [2016-10-10T18:45:57.791609 #31998] ERROR -- : Actor crashed!
18:45:58 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'beaver' (1.6.0) from the cookbook site at ''.
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:58 E, [2016-10-10T18:45:58.056110 #31998] ERROR -- : Actor crashed!
18:45:58 Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'build-essential' (3.2.0) from the cookbook site at ''.
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:126:in `find'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/community_rest.rb:102:in `download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:62:in `try_download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:36:in `block in download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `each'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/downloader.rb:35:in `download'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.2/lib/berkshelf/installer.rb:105:in `install'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
18:45:58 	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
18:45:58 Build step 'Execute shell' marked build as failure
```

**Comment by chrisgit** [comment]
Not sure if this helps but we had an issue with our private Supermarket at around the same time and resolved this by re-starting the Supermarket services. As your issue is the community supermarket then I'm not sure what the issue is.

However, we have noticed that our Supermarket cookbook has started to fail (from around 20:00 hours on 10/10/2016).

**Comment by thommay** [comment]
We had a supermarket outage last night that is probably related - http://status.chef.io/incidents/tkvw761v4ckk .

**Comment by lamont-granquist** [comment]
supermarket outage related
