### ISSUE TITLE
Berkshelf times out while uploading large cookbooks

### ISSUE THREAD

**Issue by janko-m** [berkshelf/berkshelf#1694]
We have a cookbook that has naturally grown over time, and `berks upload` has recently started throwing an error after a certain time:

<details>
<summary>task was terminated (Celluloid::Task::TerminatedError)</summary>

```
/Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each': task was terminated (Celluloid::Task::TerminatedError)
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/uploader.rb:51:in `each'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/uploader.rb:51:in `block in upload'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ridley-5.1.0/lib/ridley/client.rb:38:in `open'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ridley-5.1.0/lib/ridley.rb:56:in `open'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf.rb:166:in `ridley_connection'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/uploader.rb:50:in `upload'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/uploader.rb:37:in `run'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/berksfile.rb:593:in `upload'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/cli.rb:208:in `upload'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/cli.rb:52:in `dispatch'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/lib/berkshelf/cli.rb:27:in `execute!'
        from /Users/janko/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.5/bin/berks:5:in `<top (required)>'
        from /Users/janko/.rbenv/versions/2.3.0/bin/berks:23:in `load'
        from /Users/janko/.rbenv/versions/2.3.0/bin/berks:23:in `<main>'
```

</details>

<br>

I'm fairly certain that this error means that uploading the cookbook somehow timed out, because I regularly get it on internet with higher latency (and I haven't before), and I usually don't get it on faster internet with lower latency, and I ran `berks upload --debug` to make sure that the parts of cookbook are indeed being uploaded in both cases.

Is there a specific timeout time set inside Berkshelf itself, or is it a Celluloid thing? In any case, is there any way to remove that timeout?

**Comment by janko-m** [comment]
This error doesn't happen at the same time on each `berks upload` run, so I don't think this is an issue. I'll provide an update once I figured it out.
