### ISSUE TITLE
Berkshelf upload fails with ssl proxy error, 503 Service Unavailable

### ISSUE THREAD

**Issue by hilcharge** [berkshelf/berkshelf#1714]
Hi, currently unable to use `berkshelf upload` command, as it fails with an ssl proxy error.

I am behind corporate proxy, but the Chef server does not require use of proxy.
All proxy environment variables are not set, (`http_proxy`, `https_proxy`, `HTTP_PROXY`, `HTTPS_PROXY`).

Also, 

I am using ChefDK 2.0.2, berks version 6.2.0
Am running on cygwin, and `knife` commands are working without issue.

```
$ chef --version
Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.30.0
```

I have seen other issues about corporate proxy, but all seem to be SSL error related to untrusted certificate.
I however am not trying to verify the Certificate, and instead using `berks upload --no-ssl-verify`.

Here is the output in debug mode:

```
$ berks upload -d --no-ssl-verify
I, [2017-07-19T07:05:31.272517 #15088]  INFO -- : Checking if lockfile is trusted
D, [2017-07-19T07:05:31.273517 #15088] DEBUG -- : Checking chef-client (>= 0.0.0)
D, [2017-07-19T07:05:31.420532 #15088] DEBUG -- :   Detected there is a cached cookbook
D, [2017-07-19T07:05:31.420532 #15088] DEBUG -- :   Checking transitive dependencies for chef-client (8.1.7)
D, [2017-07-19T07:05:31.420532 #15088] DEBUG -- :     Checking cron (>= 2.0.0)
D, [2017-07-19T07:05:31.420532 #15088] DEBUG -- :     Checking transitive dependencies for cron (4.1.3)
D, [2017-07-19T07:05:31.421532 #15088] DEBUG -- :       Already checked - skipping
D, [2017-07-19T07:05:31.421532 #15088] DEBUG -- :     Checking logrotate (>= 1.9.0)
D, [2017-07-19T07:05:31.421532 #15088] DEBUG -- :     Checking transitive dependencies for logrotate (2.2.0)
D, [2017-07-19T07:05:31.421532 #15088] DEBUG -- :       Already checked - skipping
D, [2017-07-19T07:05:31.421532 #15088] DEBUG -- :     Checking windows (>= 2.0.0)
D, [2017-07-19T07:05:31.421532 #15088] DEBUG -- :     Checking transitive dependencies for windows (3.1.1)
D, [2017-07-19T07:05:31.421532 #15088] DEBUG -- :       Already checked - skipping
D, [2017-07-19T07:05:31.655555 #15088] DEBUG -- : Using 'chefignore' at 'C:/cygwin/home/username/.berkshelf/cookbooks/logrotate-2.2.0/chefignore'
I, [2017-07-19T07:05:31.821572 #15088]  INFO -- : Uploading cookbooks
D, [2017-07-19T07:05:31.821572 #15088] DEBUG -- :   No names given, using all cookbooks
I, [2017-07-19T07:05:31.931583 #15088]  INFO -- : Starting upload
D, [2017-07-19T07:05:31.961586 #15088] DEBUG -- :   Uploading chef-client (8.1.7) 'C:/cygwin/home/username/.berkshelf/cookbooks/chef-client-8.1.7'
D, [2017-07-19T07:05:32.106601 #15088] DEBUG -- : ==> performing authenticated Chef request as 'username'
D, [2017-07-19T07:05:32.106601 #15088] DEBUG -- : request env: #<struct Faraday::Env method=:get, body=nil, url=#<Addressable::URI:0x10ffb78 URI:https://mychefserver.example.com:443/organizations/redacted/cookbooks/chef-client/8.1.7>, request=#<Faraday::RequestOptions (empty)>, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v5.1.1", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"unixjp", "X-OPS-TIMESTAMP"=>"2017-07-19T06:05:32Z", "X-OPS-CONTENT-HASH"=>"2jmj7l5rSw0yVb/vlWAYkK/YBwk=", "X-OPS-AUTHORIZATION-1"=>"JpZt0wp1Llwat9035UdT7C28ENLvt/H7nlC3UYV29aGr+obpFynGcUamNiWD", "X-OPS-AUTHORIZATION-2"=>"Jb743JOPQ2NknjpS+n/2YetFEY7hkPrpIckOn88PFAFU8gX3+1ay+pLz2j8D", "X-OPS-AUTHORIZATION-3"=>"eLDAjiAl3247mOqlnBwWIuGupwkngsMb/rH/rIIP74JiVtFyoKutM0Fv83vy", "X-OPS-AUTHORIZATION-4"=>"p6EqR4MSjyLhnYEPXB44WhvCVKkXmPdIlTCfMnkX+y672/DG6v1s9XIkAtfO", "X-OPS-AUTHORIZATION-5"=>"2LxHmlPXRsAqvzVuwH3+/lts8ajqqsssKESAjWgAcCMl67o9wMk8PCMC7Ln1", "X-OPS-AUTHORIZATION-6"=>"W7XhWIRUaJAU1OYUwZMzi+PHEyb+HYBkmnT5ZDbR4w==", "HOST"=>"mychefserver.example.com:443"}, ssl=#<Faraday::SSLOptions cert_store=#<OpenSSL::X509::Store:0x345a368 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil, @_httpclient_cert_store_items=["/cygdrive/c/opscode/chefdk/embedded/ssl/cert.pem", #<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x21cb778>, issuer=#<OpenSSL::X509::Name:0x21cb790>, serial=#<OpenSSL::BN:0x21cb838>, not_before=2017-07-11 10:18:30 UTC, not_after=2027-07-09 10:18:30 UTC>]>>, parallel_manager=nil, params=nil, response=nil, response_headers=nil, status=nil, reason_phrase=nil>
E, [2017-07-19T07:05:32.151605 #15088] ERROR -- : Ridley::Errors::ClientError: connect to ssl proxy failed with status 503 Service Unavailable
E, [2017-07-19T07:05:32.152605 #15088] ERROR -- : C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/responses.rb:29:in `value'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
(celluloid):0:in `remote procedure call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/resource.rb:132:in `raw_request'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/resource.rb:123:in `request'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/resources/cookbook_resource.rb:96:in `find'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/resources/cookbook_resource.rb:190:in `upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
(celluloid):0:in `remote procedure call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/uploader.rb:51:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/uploader.rb:51:in `block in upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:38:in `open'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley.rb:56:in `open'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf.rb:175:in `ridley_connection'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/uploader.rb:50:in `upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/uploader.rb:37:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/berksfile.rb:597:in `upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/cli.rb:205:in `upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/cli.rb:49:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/cli.rb:25:in `execute!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/bin/berks:5:in `<top (required)>'
C:/opscode/chefdk/bin/berks:276:in `load'
C:/opscode/chefdk/bin/berks:276:in `<main>'
There was an error connecting to the Chef Server
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf.rb:178:in `rescue in ridley_connection'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf.rb:146:in `ridley_connection'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/uploader.rb:50:in `upload'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/uploader.rb:37:in `run'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/berksfile.rb:597:in `upload'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/cli.rb:205:in `upload'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/cli.rb:49:in `dispatch'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/lib/berkshelf/cli.rb:25:in `execute!'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.2.0/bin/berks:5:in `<top (required)>'
        C:/opscode/chefdk/bin/berks:276:in `load'
        C:/opscode/chefdk/bin/berks:276:in `<main>'

```

Also, I have tried setting `SSL_CERT_FILE`, and set no ssl verification in the config file just in case.
None of this seems to have any affect.

I unset the http_proxy and https_proxy variables after successfully running `berks install` to download the cookbooks to the workstation.

```
$ echo $SSL_CERT_FILE
/cygdrive/c/opscode/chefdk/embedded/ssl/cert.pem
$ head $SSL_CERT_FILE
##
## Bundle of CA Root Certificates
##
## Certificate data from Mozilla as of: Wed Jun  7 03:12:05 2017 GMT
##
## This is a bundle of X.509 certificates of public Certificate Authorities
## (CA). These were automatically extracted from Mozilla's root certificates
## file (certdata.txt).  This file can be found in the mozilla source tree:
## https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt
##

$ cat ~/.berkshelf/config.json
{"ssl": { "verify": false }}

$ echo $HTTP_PROXY $HTTPS_PROXY $http_proxy $https_proxy

$ cat Berksfile
source 'https://supermarket.chef.io'
cookbook 'chef-client'

```

A normal ssl connection to my Chef server is no problem without any proxy or SSL error as long as no authentication.

```
$ curl -k https://mychefserver.example.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   113    0   113    0     0    362      0 --:--:-- --:--:-- --:--:--   402<html><body>You are being <a href="https://mychefserver.example.com/login">redirected</a>.</body></html>
```

Also, `tcpdump` on the Chef server shows that nothing is being received on port 443, therefore the `berks` request is not being successfully sent to the Chef server.

This issue looks different from the other SSL error issues I have seen posted on this site, which seem related to SSL verification. 

Can anyone explain why `berks` is receiving the SSL proxy error, and/or why is a proxy being contacted in the first place?

How to fix this issue?

**Comment by lamont-granquist** [comment]
since berkshelf 7 will no longer use ridley/celluloid, closing this issue.  if it is still a problem post berkshelf 7, please open a new issue.
