### ISSUE TITLE
Ridley::Client#url_prefix message during berks upload

### ISSUE THREAD

**Issue by jwadolowski** [berkshelf/berkshelf#1716]
I upgraded to ChefDK 2.0.28 couple days ago and can see the following message during `berks upload` since then:

```
$ which berks
/opt/chefdk/bin/berks

$ berks -v
6.2.0

$ chef -v
Chef Development Kit Version: 2.0.28
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1

$ berks upload
Skipping build-essential (8.0.3) (frozen)
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded abcd-consul (0.2.1) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded consul (3.0.0) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded dnsmasq (0.2.0) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded golang (1.7.0) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded test-consul (0.1.0) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded hosts_file (0.2.2) to: 'https://chef.example.org:443/organizations/xyz'
Skipping mingw (2.0.1) (frozen)
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded nssm (3.0.2) to: 'https://chef.example.org:443/organizations/xyz'
Skipping ohai (5.1.0) (frozen)
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded poise (2.8.1) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded poise-archive (1.5.0) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded poise-service (1.5.2) to: 'https://chef.example.org:443/organizations/xyz'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded resolver (2.0.1) to: 'https://chef.example.org:443/organizations/xyz'
Skipping seven_zip (2.0.2) (frozen)
Skipping windows (3.1.1) (frozen)
```

**Comment by webframp** [comment]
Seconded, seeing the same on a new chefdk even.

```
$ chef -v
Chef Development Kit Version: 2.1.0
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1

Uploaded postgresql (6.1.1) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded powershell (6.1.0) to: 'https://fake.example.horse:443/organizations/jw'
Skipping seven_zip (2.0.2) (frozen)
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded ssh_known_hosts (5.2.1) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded users (5.1.0) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded vagrant (0.7.0) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded windows (3.1.1) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded wix (3.2.0) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded yum (5.0.1) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded yum-epel (2.1.2) to: 'https://fake.example.horse:443/organizations/jw'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded zypper (0.4.0) to: 'https://fake.example.horse:443/organizations/jw'
```

**Comment by bhechinger** [comment]
Thirded:

```
wonko@deepthought:~/learn-chef$ chef -v
Chef Development Kit Version: 2.0.28
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1

/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded chef-client (8.1.8) to: 'https://chef1-rs3x6momthbwfecd.us-east-1.opsworks-cm.io:443/organizations/default'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded compat_resource (12.19.0) to: 'https://chef1-rs3x6momthbwfecd.us-east-1.opsworks-cm.io:443/organizations/default'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded cron (4.1.3) to: 'https://chef1-rs3x6momthbwfecd.us-east-1.opsworks-cm.io:443/organizations/default'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded logrotate (2.2.0) to: 'https://chef1-rs3x6momthbwfecd.us-east-1.opsworks-cm.io:443/organizations/default'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded ohai (5.1.0) to: 'https://chef1-rs3x6momthbwfecd.us-east-1.opsworks-cm.io:443/organizations/default'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded windows (3.1.1) to: 'https://chef1-rs3x6momthbwfecd.us-east-1.opsworks-cm.io:443/organizations/default'
```

**Comment by binlialfie** [comment]
same here:

`chef -v
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded apt (6.1.4) to: 'https://chef.esv.lan:443/organizations/xxx'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded ark (1.2.0) to: 'https://chef.esv.lan:443/organizations/xxx'`

**Comment by jamesbannan** [comment]
Same here:

`Jamess-MacBook-Pro:all-nodes james$ chef -v
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
Jamess-MacBook-Pro:all-nodes james$ berks upload
Skipping all-nodes (0.1.0) (frozen)
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix`

**Comment by thommay** [comment]
Thanks for the messages; this has been fixed in head of berks already by removing ridley, and will get shipped after sufficient testing.
