### ISSUE TITLE
Some cookbooks failed to install with rubygems 2.7.6

### ISSUE THREAD

**Issue by hiroshi** [berkshelf/berkshelf#1744]
It seems that `strict_oct` is introduced from rubygems 2.7.6
https://github.com/rubygems/rubygems/commit/92e98bf8f810bd812f919120d4832df51bc25d83 
to fix this HackerOne report https://hackerone.com/reports/281336

Maybe tar archives of some cookbooks are just broken, I'm not sure....

```sh
berks install
Resolving cookbook dependencies...
Fetching 'nodebrew' from git@github.com:linyows/nodebrew-cookbook.git (at master)
Fetching 'rbenv' from git://github.com/RiotGames/rbenv-cookbook.git (at master)
Fetching 'yum' from https://github.com/opscode-cookbooks/yum.git (at master)
Fetching cookbook index from https://supermarket.getchef.com...
Installing apt (2.9.2) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing 7-zip (1.0.2) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing ark (1.1.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing bluepill (2.4.3) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing build-essential (2.4.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing chef-sugar (3.3.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing chef_handler (1.4.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing compat_resource (12.10.6) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing dmg (2.4.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing elasticsearch (2.3.2) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing ffmpeg (0.4.4) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing git (4.5.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing java (1.40.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing libvpx (1.2.2) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing limits (1.0.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing mosh (0.4.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing nginx (2.7.6) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Using nodebrew (0.3.0) from git@github.com:linyows/nodebrew-cookbook.git (at master)
Installing ohai (2.1.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing packagecloud (0.2.3) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Using rbenv (1.7.1) from git://github.com/RiotGames/rbenv-cookbook.git (at master)
Installing rbenv-install-rubies (0.2.1) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing rsyslog (4.0.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing ruby_build (0.8.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing runit (1.7.8) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing selinux (0.9.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing seven_zip (2.0.1) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing windows (1.44.1) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing x264 (0.6.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing yasm (1.0.3) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
Using yum (3.11.0) from https://github.com/opscode-cookbooks/yum.git (at master)
Installing yum-epel (0.7.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1)
/Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_header.rb:128:in `strict_oct': "\x80\x00\x00\x00p!\x8F\xB9" is not an octal string (ArgumentError)
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_header.rb:108:in `from'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_reader.rb:59:in `each'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:27:in `block in extract'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_reader.rb:29:in `new'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:118:in `reader'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:25:in `extract'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive.rb:33:in `extract'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/community_rest.rb:16:in `unpack'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/community_rest.rb:102:in `download'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:70:in `try_download'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:40:in `block in download'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:39:in `each'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:39:in `download'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/installer.rb:108:in `install'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/installer.rb:181:in `block (2 levels) in install_from_universe'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
        from /Users/hiroshi/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by balanceiskey** [comment]
I had the same issue dealing with a different package over the past two days. Manually reverting the `tar_header.rb` file referenced there appears to have allowed things to proceed, but I have to assume that's a non-ideal solution. Happy to provide additional info if it will aid debugging.

**Comment by ckeim** [comment]
Also having this issue, but in a different package - @balanceiskey what was the fix you found? Unsure of the best way to revert the tar_header.rb file.

**Comment by r4v5** [comment]
If you're curious which of your berksfile's archive(s) are failing to validate according to Gem::Package::TarHeader, you can rescue the cookbook extraction in Berkshelf: https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/community_rest.rb#L91-L105 
```diff
    def download(name, version)
      archive = stream(find(name, version)[:file])
      scratch = Dir.mktmpdir
-     extracted = self.class.unpack(archive.path, scratch)
+     begin
+       extracted = self.class.unpack(archive.path, scratch)
+     rescue
+       puts "Failed to extract! #{name} #{version} archive lacked magic header!"
+       return nil
+     end
      if File.cookbook?(extracted)
        extracted
      else
        dir = Dir.chdir(extracted) do
          Dir.glob("*").find do |dir|
            File.cookbook?(dir)
          end
        end
        File.join(extracted, dir) if dir
      end
    ensure
      archive.unlink unless archive.nil?
    end
```
The run will fail, because those cookbooks aren't extracted, but it'll at least let you know what cookbooks can be version-bumped to work around it.

For the Berksfile @hiroshi's snippet implied ([reproduced here](https://gist.github.com/r4v5/04079f23cbf6506343da6b7304dc8465) in a gist) I got the following failures:
```
Failed to extract! libvpx 1.2.2 archive lacked magic header!
Using yum (3.11.0)
Using yum-epel (0.7.0)
Failed to extract! x264 0.6.0 archive lacked magic header!
Failed to extract! yasm 1.0.3 archive lacked magic header!
```

For better or worse, you can't (straightforwardly) monkeypatch a bypass for Gem::Package::TarHeader from a Berksfile, so the short-term option seems to be to downgrade to a version that doesn't include the updated gem.

**Comment by ckeim** [comment]
Thank you! I ended up reverting back to 2.7.4 gem as it seemed to be the quickest solution for now.

**Comment by shanewarner** [comment]
@ckeim can you describe how you downgraded to 2.7.4 to fix this? I've tried gem installing it specifying the version but it still seems to throw the same error?

**Comment by hiroshi** [comment]
Try this.
```sh
gem update --system 2.7.5
````
2.7.6 is affected version, 2.7.5 work for me

**Comment by b-dean** [comment]
@r4v5 What did you mean when you said
> The run will fail, because those cookbooks aren't extracted, but it'll at least let you know what cookbooks can be version-bumped to work around it.

What do you have to do to a cookbook to fix it so it doesn't lack the "magic header"?

**Comment by lamont-granquist** [comment]
seems to be an upstream bug in rubygems:

https://github.com/rubygems/rubygems/issues/2213

**Comment by jeffbyrnes** [comment]
Ugh, sorry for all the references. I was trying to solve this, just realized it was spamming in here.

I was attempting to debug the aforementioned fix on Travis CI while using Chef DK: `chef exec gem update --system 2.7.5`.

If the last one doesn't fix it, I’ll rip out the reference on my next amend to that commit.

**Comment by jeffbyrnes** [comment]
Ok, one more mention (sorry), with my actual, working fix. Maybe it will help someone!

**Comment by thommay** [comment]
chef/mixlib-archive#17 ought to eventually fix this.

**Comment by hiroshi** [comment]
I tried with mixlib-archive@0.4.2, but same result.
<a href="https://gyazo.com/d81510ded4ed6d01bed341e3ec33f873"><img src="https://i.gyazo.com/d81510ded4ed6d01bed341e3ec33f873.png" alt="https://gyazo.com/d81510ded4ed6d01bed341e3ec33f873" width="860"/></a>

**Comment by thommay** [comment]
@hiroshi there are a bunch of dependencies that you'd need - you'll need libarchive.so and the ffi-libarchive gem. We'll ship them in ChefDK but if you hand install berkshelf you'll need to install all that manually.

**Comment by hiroshi** [comment]
> if you hand install berkshelf

I'm using bundler, and i did `bundle update mixlib-archive` to update mixlib-archive to 0.4.2.
If the version of mixlib-archive needs certain versions of dependent gems to work correctly, it should be described in the gemspec of mixlib-archive. Right?

**Comment by thommay** [comment]
The gem dependencies are optional, and they have hard dependencies on system libraries that we can't guarantee will exist. So, no - they're not in the gemspec.
