### ISSUE TITLE
berks upload failure on 7.0.0

### ISSUE THREAD

**Issue by lamont-granquist** [berkshelf/berkshelf#1748]
```
% cat Berksfile
source :chef_server

metadata
```

```
% cat Berksfile.lock
DEPENDENCIES
  test
    path: .
    metadata: true

GRAPH
  build-essential (8.0.0)
    mingw (>= 1.1)
    seven_zip (>= 0.0.0)
  mingw (2.0.0)
    seven_zip (>= 0.0.0)
  seven_zip (2.0.2)
    windows (>= 1.2.2)
  test (0.0.1)
    build-essential (>= 0.0.0)
```

```
% berks upload -d
I, [2018-03-21T10:46:34.601181 #24537]  INFO -- : Checking if lockfile is trusted
D, [2018-03-21T10:46:34.601263 #24537] DEBUG -- : Checking test (>= 0.0.0)
D, [2018-03-21T10:46:34.603603 #24537] DEBUG -- :   Detected there is a cached cookbook
D, [2018-03-21T10:46:34.603774 #24537] DEBUG -- :   Checking transitive dependencies for test (0.0.1)
D, [2018-03-21T10:46:34.603794 #24537] DEBUG -- :     Checking build-essential (>= 0.0.0)
D, [2018-03-21T10:46:34.603822 #24537] DEBUG -- :     Checking transitive dependencies for build-essential (8.0.0)
D, [2018-03-21T10:46:34.603836 #24537] DEBUG -- :       Already checked - skipping
I, [2018-03-21T10:46:34.630122 #24537]  INFO -- : Uploading cookbooks
D, [2018-03-21T10:46:34.630162 #24537] DEBUG -- :   No names given, using all cookbooks
D, [2018-03-21T10:46:34.630184 #24537] DEBUG -- :   Looking up dependencies for test
D, [2018-03-21T10:46:34.630203 #24537] DEBUG -- :   Looking up dependencies for build-essential
D, [2018-03-21T10:46:34.630217 #24537] DEBUG -- :   Looking up dependencies for mingw
D, [2018-03-21T10:46:34.630230 #24537] DEBUG -- :   Looking up dependencies for seven_zip
NoMethodError undefined method `dependencies' for nil:NilClass
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:105:in `block in lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `each'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:105:in `block in lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `each'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:105:in `block in lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `each'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:105:in `block in lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `each'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:98:in `lookup_dependencies'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:127:in `block in filtered_cookbooks'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:126:in `each'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:126:in `filtered_cookbooks'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/uploader.rb:33:in `run'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/berksfile.rb:573:in `upload'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/cli.rb:195:in `upload'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/cli.rb:47:in `dispatch'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/lib/berkshelf/cli.rb:23:in `execute!'
	/Users/lamont/.rvm/gems/ruby-2.4.3/gems/berkshelf-7.0.0.alpha.0/bin/berks:5:in `<top (required)>'
	/Users/lamont/.rvm/gems/ruby-2.4.3/bin/berks:23:in `load'
	/Users/lamont/.rvm/gems/ruby-2.4.3/bin/berks:23:in `<main>'
	/Users/lamont/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
	/Users/lamont/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lamont-granquist** [comment]
ehrm, yeah, so I've got seven_zip in my solution which depends on windows, which isn't in my solution.   and for some reason i was testing against a `:chef_server` source which suggests to me that somehow this damage is mostly self-inflicted.

maybe the error message could be better here, but this looks less like a regression and more like user error.
