### ISSUE TITLE
Broken ENV["BERKSHELF_PATH"] logic in specs 

### ISSUE THREAD

**Issue by 375gnu** [berkshelf/berkshelf#1751]
In spec_helper.rb you have
```ruby
  config.before(:all) do
    ENV["BERKSHELF_PATH"] = berkshelf_path.to_s
  end

  config.before(:each) do
    clean_tmp_path
    Berkshelf.initialize_filesystem
    Berkshelf::CookbookStore.instance.initialize_filesystem
    reload_configs
  end
```

With this you try to set clean berkshelf directory before every test call.

But then you have 

```ruby
require "berkshelf"
```

which has memoized `berkshelf_path`:
```ruby
    def berkshelf_path
      @berkshelf_path ||= File.expand_path(ENV["BERKSHELF_PATH"] || "~/.berkshelf")
    end
```

What does it mean? It means that in all calls to Berkshelf.initialize_filesystem you use already saved value of `@berkshelf_path`, e.g. `"~/.berkshelf"`. And if your used doesn't have writeable home, all your tests fail:

```
  1) .formatter with default formatter is human readable
     Failure/Error: FileUtils.mkdir_p(berkshelf_path, mode: 0755)
     
     Errno::EACCES:
       Permission denied @ dir_s_mkdir - /.berkshelf
     # ./lib/berkshelf.rb:134:in `initialize_filesystem'
     # ./spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
```

Here there the result of `puts caller` inside `berkshelf_path` method called on `require "berkshelf"`:
```
/tmp/berkshelf/lib/berkshelf/config.rb:9:in `store_location'
/tmp/berkshelf/lib/berkshelf/config.rb:19:in `path'
/tmp/berkshelf/lib/berkshelf/config.rb:36:in `file'
/tmp/berkshelf/lib/berkshelf/config.rb:45:in `instance'
/tmp/berkshelf/lib/berkshelf.rb:110:in `config'
/tmp/berkshelf/lib/berkshelf/cookbook_generator.rb:50:in `<class:CookbookGenerator>'
/tmp/berkshelf/lib/berkshelf/cookbook_generator.rb:2:in `<module:Berkshelf>'
/tmp/berkshelf/lib/berkshelf/cookbook_generator.rb:1:in `<top (required)>'
/tmp/berkshelf/lib/berkshelf/cli.rb:4:in `require_relative'
/tmp/berkshelf/lib/berkshelf/cli.rb:4:in `<top (required)>'
/tmp/berkshelf/lib/berkshelf.rb:241:in `require_relative'
/tmp/berkshelf/lib/berkshelf.rb:241:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/tmp/berkshelf/spec/spec_helper.rb:74:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/tmp/berkshelf/spec/unit/berkshelf_spec.rb:1:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1954:in `load'
/usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1954:in `load_spec_file_handling_errors'
/usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1496:in `block in load_spec_files'
/usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1494:in `each'
/usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1494:in `load_spec_files'
/usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:100:in `setup'
/usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:86:in `run'
/usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:71:in `run'
/usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:45:in `invoke'
/usr/bin/rspec:4:in `<main>'
```

**Comment by lamont-granquist** [comment]
this is deep down into a use case we don't support.  you should really be using chefdk.  even for Gemfile installations of berkshelf, you don't need to be running the spec tests.  and if you are, then i think its reasonable that it is a requirement to run them as a user with a writable home directory.

**Comment by 375gnu** [comment]
Do you mean "we don't fix broken code"?
