### ISSUE TITLE
NoMethodError caused by ohai configuration parameter in knife.rb

### ISSUE THREAD

**Issue by syndesis** [berkshelf/berkshelf#1754]
```
$ berks --version
6.3.1
$ cat > ~/.chef/knife.rb
ohai.disabled_plugins = [:Passwd]
$ berks --version
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-config-13.8.5/lib/chef-config/workstation_config_loader.rb:203:in `rescue in apply_config': You have an error in your config file /Users/username/.chef/knife.rb (ChefConfig::ConfigurationError)

NoMethodError: undefined method `disabled_plugins=' for nil:NilClass
  /Users/username/.chef/knife.rb:1:in `from_string'
Relevant file content:
  1: ohai.disabled_plugins = [:Passwd]
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-config-13.8.5/lib/chef-config/workstation_config_loader.rb:181:in `apply_config'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-config-13.8.5/lib/chef-config/workstation_config_loader.rb:82:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/chef/config.rb:13:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf.rb:110:in `new'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf.rb:110:in `chef_config'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/config.rb:97:in `<class:Config>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/config.rb:5:in `<module:Berkshelf>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/config.rb:4:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/cookbook_generator.rb:3:in `require_relative'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/cookbook_generator.rb:3:in `<class:CookbookGenerator>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/cookbook_generator.rb:2:in `<module:Berkshelf>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/cookbook_generator.rb:1:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf.rb:228:in `require_relative'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf.rb:228:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/cli.rb:1:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/bin/berks:3:in `<top (required)>'
	from /usr/local/bin/berks:250:in `load'
	from /usr/local/bin/berks:250:in `<main>'
```

**Comment by lamont-granquist** [comment]
I think this is already fixed in 7.0.0 / master but the other regressions in master are blocking me testing it.
