### ISSUE TITLE
Berkshelf 7.0.0 doesn't work with github enterprise endpoint

### ISSUE THREAD

**Issue by xeron** [berkshelf/berkshelf#1764]
This configuration was working before upgrade to `7.0.0`.

`Berksfile`:

```
source 'https://[REDACTED]'

metadata

cookbook 'aws', github: 'chef-cookbooks/aws', tag: 'v3.4.1'
cookbook 'ohai', github: 'chef-cookbooks/ohai', tag: 'v2.1.0'

group :package do
  cookbook 'chef-metrics'
end
```

`~/.berkshelf/config.json`:

```
{
  "github": [
    {
      "access_token": "[REDACTED]",
      "api_endpoint": "https://[REDACTED]/api/v3",
      "web_endpoint": "https://[REDACTED]",
      "ssl_verify": true
    }
  ]
}
```

Trying to install:

```
$ berks install -d
An error occurred while reading the Berksfile:

  No such file or directory @ rb_sysopen - {
  "github": [
    {
      "access_token": "[REDACTED]",
      "api_endpoint": "https://[REDACTED]/api/v3",
      "web_endpoint": "https://[REDACTED]",
      "ssl_verify": true
    }
  ]
}

	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/mixlib-config-2.2.6/lib/mixlib/config.rb:82:in `read'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/mixlib-config-2.2.6/lib/mixlib/config.rb:82:in `from_json'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/config.rb:112:in `method_missing'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/config.rb:87:in `from_json'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/config.rb:56:in `instance'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/source.rb:172:in `api_timeout'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/source.rb:17:in `initialize'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/berksfile.rb:208:in `new'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/berksfile.rb:208:in `source'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `public_send'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `block (3 levels) in cleanroom'
	/Users/ilarionov/Projects/Twilio/prvoice-cookbooks/voice-cache-ats/Berksfile:1:in `evaluate'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `instance_eval'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `evaluate'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/cleanroom-1.0.0/lib/cleanroom.rb:56:in `evaluate_file'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/cleanroom-1.0.0/lib/cleanroom.rb:173:in `evaluate_file'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/berksfile.rb:27:in `from_file'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/berksfile.rb:16:in `from_options'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/cli.rb:130:in `install'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/cli.rb:47:in `dispatch'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/lib/berkshelf/cli.rb:23:in `execute!'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.0/bin/berks:5:in `<top (required)>'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/bin/berks:23:in `load'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/bin/berks:23:in `<main>'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	/Users/ilarionov/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xeron** [comment]
@lamont-granquist it's still sort of broken, with `7.0.1` it tries to use public github even with configuration being set to use GHE:

```
…
D, [2018-05-01T15:50:39.657651 #56074] DEBUG -- :   Downloading apt (1.4.2) from https://PRIVATE_BERKSHELF_ADDRESS
D, [2018-05-01T15:50:39.660284 #56074] DEBUG -- :     => #<Berkshelf::APIClient::RemoteCookbook:0x00007fdaef47e998 @name="apt", @version="1.4.2", @attributes={"endpoint_priority"=>3, "platforms"=>{"ubuntu"=>">= 0.0.0", "debian"=>">= 0.0.0"}, "dependencies"=>{}, "location_type"=>"github", "location_path"=>"https://PRIVATE_GHE_ADDRESS/chef-cookbooks/apt"}>
Installing apt (1.4.2) from https://PRIVATE_BERKSHELF_ADDRESS ([github] https://PRIVATE_GHE_ADDRESS/chef-cookbooks/apt)
…
Installing yum (3.5.2) from https://PRIVATE_BERKSHELF_ADDRESS ([github] https://PRIVATE_GHE_ADDRESS/chef-cookbooks/yum)
Octokit::NotFound HEAD https://api.github.com/repos/chef-cookbooks/apt/tarball/v1.4.2: 404 - 
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.0/lib/faraday/response.rb:9:in `block in call'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.0/lib/faraday/response.rb:61:in `on_complete'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.0/lib/faraday/response.rb:8:in `call'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/faraday-0.15.0/lib/faraday/connection.rb:138:in `head'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/octokit-4.8.0/lib/octokit/client/contents.rb:157:in `archive_link'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.1/lib/berkshelf/downloader.rb:117:in `try_download'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.1/lib/berkshelf/downloader.rb:41:in `block in download'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.1/lib/berkshelf/downloader.rb:40:in `each'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.1/lib/berkshelf/downloader.rb:40:in `download'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.1/lib/berkshelf/installer.rb:108:in `install'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/berkshelf-7.0.1/lib/berkshelf/installer.rb:181:in `block (2 levels) in install_from_universe'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
  /Users/ilarionov/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by lamont-granquist** [comment]
also nothing obvious changed in the downloader and nothing changed in the installer between 6.3.2 and 7.0.2

**Comment by xeron** [comment]
6.3.2:

```
#<VariaModel::Attributes access_token="…" api_endpoint="https://…/api/v3" ssl_verify=true web_endpoint="https://…">
```

7.0.2:

```
{"access_token"=>"…", "api_endpoint"=>"https://…/api/v3", "web_endpoint"=>"https://…", "ssl_verify"=>true}
```

```
(byebug) puts options
nil
{"access_token"=>"…", "api_endpoint"=>"https://…/api/v3", "web_endpoint"=>"https://…", "ssl_verify"=>true}
(byebug) puts options[:api_endpoint]

nil
(byebug) puts options['api_endpoint']
nil
(byebug) https://…/api/v3
nil
```

@lamont-granquist is it helpful? ^^

You've changed some `VariaModel::Attributes` class to just a `Hash`.

`options[:api_endpoint]` and `options['api_endpoint']` is not the same anymore.

**Comment by xeron** [comment]
Is anyone working on the fix? I mean, I already showed you the source of regression, would be great to see some progress here :(

**Comment by xeron** [comment]
@lamont-granquist please, I keep suggesting ppl to downgrade chef-dk due to this bug. Can we merge my PR which fixes it?
