### ISSUE TITLE
Could not find 'berkshelf

### ISSUE THREAD

**Issue by deon609** [berkshelf/berkshelf#1797]
Hi, I have an ran into an issue with berks. Unable to upload cookbooks.

```
berks --version
Traceback (most recent call last):
	3: from /usr/local/bin/berks:22:in `<main>'
	2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	1: from /usr/lib/ruby/2.5.0/rubygems/dependency.rb:322:in `to_spec'
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'berkshelf' (>= 0.a) among 38 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/deon/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
```
My chefdk version:
```
chef -v
Chef Development Kit Version: 3.3.23
chef-client version: 14.5.33
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.112
```

**Comment by deon609** [comment]
Got it fixed with `sudo gem install berkshelf`
