### ISSUE TITLE
conflicting chdir during another chdir block, while using kitchen converge with concurrency

### ISSUE THREAD

**Issue by xblitz** [berkshelf/berkshelf#1798]
While running `kitchen converge --concurrency 9` I see this warning appear on screen:
``` /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:34: warning: conflicting chdir during another chdir block```
and the converge fails,   then looking in the logs I have this:
```I, [2018-10-22T22:23:43.377787 #9698]  INFO -- jenkins-centos-67: -----> Creating <jenkins-centos-67>...
I, [2018-10-22T22:23:43.496365 #9698]  INFO -- jenkins-centos-67: If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

I, [2018-10-22T22:23:44.325134 #9698]  INFO -- jenkins-centos-67: Instance <i-xxxxxxxxxxxxxxxxx> requested.
I, [2018-10-22T22:23:44.325457 #9698]  INFO -- jenkins-centos-67: Polling AWS for existence, attempt 0...
I, [2018-10-22T22:23:44.463479 #9698]  INFO -- jenkins-centos-67: Attempting to tag the instance, 0 retries
I, [2018-10-22T22:23:44.694381 #9698]  INFO -- jenkins-centos-67: EC2 instance <i-xxxxxxxxxxxxxxxxx> created.
I, [2018-10-22T22:23:44.767536 #9698]  INFO -- jenkins-centos-67: Waited 0/300s for instance <i-xxxxxxxxxxxxxxxxx> volumes to be ready.
I, [2018-10-22T22:23:45.320149 #9698]  INFO -- jenkins-centos-67: Waited 0/300s for instance <i-xxxxxxxxxxxxxxxxx> to become ready.
I, [2018-10-22T22:24:15.422218 #9698]  INFO -- jenkins-centos-67: Waited 30/300s for instance <i-xxxxxxxxxxxxxxxxx> to become ready.
I, [2018-10-22T22:24:45.620452 #9698]  INFO -- jenkins-centos-67: Waited 60/300s for instance <i-xxxxxxxxxxxxxxxxx> to become ready.
I, [2018-10-22T22:24:45.756363 #9698]  INFO -- jenkins-centos-67: EC2 instance <i-xxxxxxxxxxxxxxxxx> ready (hostname: xxxxxxxxxxxxxx.us-west-1.compute.amazonaws.com).
I, [2018-10-22T22:24:45.957836 #9698]  INFO -- jenkins-centos-67: [SSH] Established
I, [2018-10-22T22:24:45.959604 #9698]  INFO -- jenkins-centos-67: Finished creating <jenkins-centos-67> (1m2.57s).
I, [2018-10-22T22:24:45.959793 #9698]  INFO -- jenkins-centos-67: -----> Converging <jenkins-centos-67>...
I, [2018-10-22T22:24:45.963808 #9698]  INFO -- jenkins-centos-67: Preparing files for transfer
I, [2018-10-22T22:24:45.980548 #9698]  INFO -- jenkins-centos-67: Preparing dna.json
I, [2018-10-22T22:25:16.460632 #9698]  INFO -- jenkins-centos-67: Resolving cookbook dependencies with Berkshelf 7.0.6...
E, [2018-10-22T22:25:16.499976 #9698] ERROR -- jenkins-centos-67: Converge failed on instance <jenkins-centos-67>.
E, [2018-10-22T22:25:16.500197 #9698] ERROR -- jenkins-centos-67: ------Exception-------
E, [2018-10-22T22:25:16.500271 #9698] ERROR -- jenkins-centos-67: Class: Berkshelf::BerksfileReadError
E, [2018-10-22T22:25:16.500324 #9698] ERROR -- jenkins-centos-67: Message: An error occurred while reading the Berksfile:

  No such file or directory @ rb_sysopen - certificate.crt
E, [2018-10-22T22:25:16.500374 #9698] ERROR -- jenkins-centos-67: ----------------------
E, [2018-10-22T22:25:16.502539 #9698] ERROR -- jenkins-centos-67: ------Backtrace-------
E, [2018-10-22T22:25:16.502632 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:36:in `read'
E, [2018-10-22T22:25:16.502687 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:36:in `block (2 levels) in set_custom_certs'
E, [2018-10-22T22:25:16.502741 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:35:in `each'
E, [2018-10-22T22:25:16.510654 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:35:in `block in set_custom_certs'
E, [2018-10-22T22:25:16.510747 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:34:in `chdir'
E, [2018-10-22T22:25:16.510825 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:34:in `set_custom_certs'
E, [2018-10-22T22:25:16.510934 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ssl_policies.rb:15:in `initialize'
E, [2018-10-22T22:25:16.510988 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/source.rb:57:in `new'
E, [2018-10-22T22:25:16.511125 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/source.rb:57:in `ssl_policy'
E, [2018-10-22T22:25:16.512721 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/source.rb:52:in `initialize'
E, [2018-10-22T22:25:16.512803 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/berksfile.rb:208:in `new'
E, [2018-10-22T22:25:16.512929 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/berksfile.rb:208:in `source'
E, [2018-10-22T22:25:16.513007 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `public_send'
E, [2018-10-22T22:25:16.513082 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `block (3 levels) in cleanroom'
E, [2018-10-22T22:25:16.513156 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/Berksfile:1:in `evaluate'
E, [2018-10-22T22:25:16.513229 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `instance_eval'
E, [2018-10-22T22:25:16.513301 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `evaluate'
E, [2018-10-22T22:25:16.513377 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:56:in `evaluate_file'
E, [2018-10-22T22:25:16.513450 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:173:in `evaluate_file'
E, [2018-10-22T22:25:16.513523 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/berksfile.rb:27:in `from_file'
E, [2018-10-22T22:25:16.513596 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef/berkshelf.rb:62:in `block in resolve'
E, [2018-10-22T22:25:16.513671 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/shell/basic.rb:20:in `mute'
E, [2018-10-22T22:25:16.513745 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef/berkshelf.rb:61:in `resolve'
E, [2018-10-22T22:25:16.513817 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef/common_sandbox.rb:328:in `block in resolve_with_berkshelf'
E, [2018-10-22T22:25:16.513912 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef/common_sandbox.rb:325:in `synchronize'
E, [2018-10-22T22:25:16.514630 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef/common_sandbox.rb:325:in `resolve_with_berkshelf'
E, [2018-10-22T22:25:16.516904 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef/common_sandbox.rb:259:in `prepare_cookbooks'
E, [2018-10-22T22:25:16.517451 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef/common_sandbox.rb:48:in `populate'
E, [2018-10-22T22:25:16.517519 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef_base.rb:251:in `create_sandbox'
E, [2018-10-22T22:25:16.517595 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/chef_zero.rb:50:in `create_sandbox'
E, [2018-10-22T22:25:16.517683 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-10-22T22:25:16.517785 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:408:in `block in converge_action'
E, [2018-10-22T22:25:16.519032 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2018-10-22T22:25:16.519113 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2018-10-22T22:25:16.519188 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-10-22T22:25:16.519264 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2018-10-22T22:25:16.519337 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:404:in `converge_action'
E, [2018-10-22T22:25:16.519412 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2018-10-22T22:25:16.519486 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2018-10-22T22:25:16.519559 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-10-22T22:25:16.519637 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-10-22T22:25:16.519710 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-10-22T22:25:16.519784 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:140:in `converge'
E, [2018-10-22T22:25:16.521660 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-10-22T22:25:16.522354 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-10-22T22:25:16.522986 #9698] ERROR -- jenkins-centos-67: /var/lib/jenkins/workspace/cookbook/.bundle/ruby/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-10-22T22:25:16.523979 #9698] ERROR -- jenkins-centos-67: ----End Backtrace-----
```
the certificate file of exists, as it fails intermittently and on random suites.

seems to be a similar issue as https://github.com/test-kitchen/test-kitchen/issues/1416

**Comment by xblitz** [comment]
I think the issue in the case of usage with test-kitchen concurrency is that berks is loaded as a library, and many thread start the their own berks usage, but end up in the "chdir" from ssl_policies.rb around the same time, and else from other chdir's of test-kitchen , even if it has been made "thread-safe" in test-kitchen with a mutex,  that mutex is only good within test-kitchen

**Comment by stevenoneill** [comment]
ive seem this as well and been meaning to open an issue...also cant think of a great solution yet

**Comment by xblitz** [comment]
Actually, rethinking about the issue, I see 2 approaches:

- from berkshelf:
remove usage of chdir if it's possible (though I think a windows issue is the cause of the use)
- from kitchen:
have an internal mutex when calling the berkshelf methods that need to chdir

and maybe a third one though:
- berkshelf and kitchen:
have a mutex in berkshelf, that can be set from outside when using as a library, so kitchen could reference it's own mutex

**Comment by lamont-granquist** [comment]
test-kitchen should not use berkshelf as a library:

https://github.com/test-kitchen/test-kitchen/issues/1307

also see:

https://github.com/berkshelf/berkshelf#cli-usage

**Comment by stevenoneill** [comment]
So like, here?

https://github.com/test-kitchen/test-kitchen/blame/9c771433645495500f0c6da21927208826ec8d5d/lib/kitchen/provisioner/chef/berkshelf.rb#L97

**Comment by xblitz** [comment]
It's not a change, it's always been like that in kitchen from what I know.   I've went back 6 years in commits and see those require 'berkshelf' ...

**Comment by stevenoneill** [comment]
That's my understanding now, too.  So maybe an option could be analyzing the way Policyfiles did it and re-implementing, as referenced by coderanger's comment https://github.com/test-kitchen/test-kitchen/issues/1307#issuecomment-340085063

**Comment by lamont-granquist** [comment]
yes its always been that way it t-k, but that be changed.

**Comment by lamont-granquist** [comment]
i think i'm going to be more assertive here -- this won't be fixed in berkshelf and test-kitchen/test-kitchen#1307 is the correct bug to fix this issue.
