### ISSUE TITLE
Berks upload fails for invalid metadata dependencies

### ISSUE THREAD

**Issue by pcantea** [berkshelf/berkshelf#1807]
### Issue
Berks upload of a single cookbook fails if there are invalid metadata dependencies with no useful error message
```
E, [2019-01-15T08:42:47.349558 #5770] ERROR -- : Net::HTTPServerException: 400 "Bad Request"
E, [2019-01-15T08:42:47.349640 #5770] ERROR -- : /opt/chefdk/embedded/lib/ruby/2.5.0/net/http/response.rb:122:in `error!'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33/lib/chef/http.rb:152:in `request'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33/lib/chef/http.rb:123:in `put'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33/lib/chef/cookbook_uploader.rb:103:in `block in upload_cookbooks'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33/lib/chef/cookbook_uploader.rb:97:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33/lib/chef/cookbook_uploader.rb:97:in `upload_cookbooks'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/uploader.rb:79:in `block (2 levels) in upload'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/uploader.rb:61:in `map'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/uploader.rb:61:in `block in upload'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/ridley_compat.rb:56:in `new_client'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf.rb:172:in `ridley_connection'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/uploader.rb:55:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/uploader.rb:42:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/berksfile.rb:576:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:195:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:47:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:23:in `execute!'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/bin/berks:5:in `<top (required)>'
/usr/local/bin/berks:293:in `load'
/usr/local/bin/berks:293:in `<main>'
There was an error connecting to the Chef Server
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf.rb:177:in `rescue in ridley_connection'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf.rb:144:in `ridley_connection'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/uploader.rb:55:in `upload'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/uploader.rb:42:in `run'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/berksfile.rb:576:in `upload'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:195:in `upload'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:47:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/lib/berkshelf/cli.rb:23:in `execute!'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.6/bin/berks:5:in `<top (required)>'
	/usr/local/bin/berks:293:in `load'
	/usr/local/bin/berks:293:in `<main>'
```

Berks install doesn't raise any issues, however if I try to upload the same cookbook with knife I get 
```
ERROR: /cookbooks failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Invalid value '~> 7' for metadata.dependencies"]}
```

**Comment by annycool007** [comment]
I am facing another issue with the same berks upload command
