### ISSUE TITLE
After upgrade to berkshelf 7 "berks install" command fails trying to access /etc/chef/client.pem

### ISSUE THREAD

**Issue by koertkuipers** [berkshelf/berkshelf#1811]
on server:
```
$ sudo chef-server-ctl version
12.18.14
```

on laptop in cookbook directory:
```
$ berks --version
6.3.4
$ more Berksfile
source "https://supermarket.getchef.com"
source :chef_server

metadata

$ more ~/.berkshelf/config.json
{
    "ssl": {
	"verify": false
    },
    "chef": {
       "chef_server_url": "https://mychefserver/organizations/myorg",
       "node_name": "koert",
       "client_key": "/home/koert/.berkshelf/koert.pem"
    }
}
$ berks install
Resolving cookbook dependencies...
Fetching 'thiscookbook' from source at .
Fetching cookbook index from chef_server: https://mychefserver/organizations/myorg...
Fetching cookbook index from https://supermarket.getchef.com...
Using thiscookbook (0.5.1) from source at .
Installing thatcookbook (1.1.0) from chef_server: https://mychefserver/organizations/myorg ([chef_server] https://mychefserver/organizations/myorg)
```

now i update my chefdk to 3.6.57 so that berks 7.0.7 is installed. i also remove the cached cookbook so it needs to be installed again.
```
rm -r ~/.berkshelf/cookbooks/thatcookbook-1.1.0

$ berks --version
7.0.7

$ berks install
Resolving cookbook dependencies...
Fetching 'thiscookbook' from source at .
Fetching cookbook index from chef_server: https://mychefserver/organizations/myorg...
Fetching cookbook index from https://supermarket.getchef.com...
Installing thatcookbook (1.1.0) from chef_server: https://mychefserver/organizations/myorg ([chef_server] https://mychefserver/organizations/myorg)
[2019-01-19T03:25:02-05:00] WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::EACCES: Permission denied @ rb_sysopen - /etc/chef/client.pem>
Chef::Exceptions::PrivateKeyMissing I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
```

why is berks 7 trying to access /etc/chef/client.pem when i specify that my pem file is ~/.berkshelf/config.json?

with --debug the stacktrace is:
```
Chef::Exceptions::PrivateKeyMissing I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/http/authenticator.rb:98:in `rescue in load_signing_key'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/http/authenticator.rb:84:in `load_signing_key'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/http/authenticator.rb:42:in `initialize'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/http.rb:98:in `new'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/http.rb:98:in `block in initialize'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/http.rb:97:in `each'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/http.rb:97:in `initialize'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/server_api.rb:40:in `initialize'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/cookbook_version.rb:457:in `new'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/cookbook_version.rb:457:in `chef_server_rest'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/cookbook_version.rb:467:in `load'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/downloader.rb:87:in `block in try_download'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/ridley_compat.rb:56:in `new_client'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/downloader.rb:86:in `try_download'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/downloader.rb:41:in `block in download'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/downloader.rb:40:in `each'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/downloader.rb:40:in `download'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/installer.rb:108:in `install'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.7/lib/berkshelf/installer.rb:137:in `block (2 levels) in install_from_lockfile'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/ivar.rb:169:in `safe_execute'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/future.rb:55:in `block in execute'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by koertkuipers** [comment]
it also seems `--config` is no longer respected by berks? i tried using `berks install --config ~/.berkshelf/config.json`
