### ISSUE TITLE
Berkshelf 7.0.7 ignores ~/.berkshelf/config.json 

### ISSUE THREAD

**Issue by madwort** [berkshelf/berkshelf#1812]
Berkshelf 7.0.7, ruby 2.5.1, does not read config settings from `~/.berkshelf/config.json` but will read settings from `$PWD/.berkshelf/config.json`. 

Manifests for me as:

```
$ cat ~/.berkshelf/config.json
{
  "github": [
    {
      "access_token": "[REDACTED]"
    }
  ]
}
$ bundle exec berks vendor cookbooks
Resolving cookbook dependencies...
Fetching 'current-cookbook' from source at .
Fetching cookbook index from https://blahblah.com
Installing private-repo (x.y.z) from https://blahblah.com ([github] https://github.com/blahblah/private-repo)
Octokit::NotFound HEAD https://api.github.com/repos/blahblah/private-repo/tarball/vx.y.z: 404 - 
```
workaround:
```
$ cp ~/.berkshelf/config.json ./.berkshelf/config.json
$ bundle exec berks vendor cookbooks
Resolving cookbook dependencies...
Fetching 'current-cookbook' from source at .
Fetching cookbook index from https://berkshelf.transportapi.com...
Installing private-repo (x.y.z) from https://blahblah.com ([github] https://github.com/blahblah/private-repo)
Vendoring private-repo (x.y.z) to cookbooks/private-repo
```

This may be a duplicate of https://github.com/berkshelf/berkshelf/issues/1811

**Comment by madwort** [comment]
(the old config file was working fine with berkshelf `6.3.4`)

**Comment by madwort** [comment]
Alternate workaround:
```
BERKSHELF_CONFIG=~/.berkshelf/config.json bundle exec berks vendor cookbooks
```

Note that README.md currently still says 
```
Berkshelf will search in specific locations for a configuration file. In order:

$PWD/.berkshelf/config.json
~/.berkshelf/config.json
```

**Comment by madwort** [comment]
btw, tried adding this to `~/.chef/knife.rb` (which I can demonstrate is being read by berkshelf) but doesn't appear to help:
```
knife[:github] = [{"access_token" => "REDACTED"}]
```

**Comment by lamont-granquist** [comment]
errors in parsing config.json are unlikely to ever get fixed.  if i get some time i'm more likely to work on formal deprecation of config.json in #1785

**Comment by madwort** [comment]
Thanks @lamont-granquist , I understand that config.json errors are unlikely to get fixed, I mostly created this thread to help out other people that hit this same issue.
However, if you have any thoughts on how to get a github `access_token` working for berkshelf via `knife.rb`, I'd very interested in hearing them!

**Comment by kahamed** [comment]
same issue in 7.0.8 also, berkshelf is ignoring the config file

$ berks apply prs_qa_uw2_888 -c ./.berkshelf/bps_config.json -d
[2019-04-25T15:50:48+00:00] WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::EACCES: Permission denied @ rb_sysopen - /etc/chef/client.pem>
E, [2019-04-25T15:50:48.574246 #17359] ERROR -- : Chef::Exceptions::PrivateKeyMissing: I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
E, [2019-04-25T15:50:48.574356 #17359] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/http/authenticator.rb:98:in `rescue in load_signing_key'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/http/authenticator.rb:84:in `load_signing_key'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/http/authenticator.rb:42:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/http.rb:98:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/http.rb:98:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/http.rb:97:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/http.rb:97:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/server_api.rb:40:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/environment.rb:49:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/environment.rb:49:in `chef_server_rest'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.3/lib/chef/environment.rb:277:in `save'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/lockfile.rb:224:in `block in apply'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/ridley_compat.rb:56:in `new_client'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf.rb:172:in `ridley_connection'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/lockfile.rb:215:in `apply'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:221:in `apply'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:47:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:23:in `execute!'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/bin/berks:5:in `<top (required)>'
/opt/chefdk/bin/berks:308:in `load'
/opt/chefdk/bin/berks:308:in `<main>'
There was an error connecting to the Chef Server
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf.rb:177:in `rescue in ridley_connection'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf.rb:144:in `ridley_connection'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/lockfile.rb:215:in `apply'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:221:in `apply'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:47:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:23:in `execute!'
	/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/berkshelf-7.0.8/bin/berks:5:in `<top (required)>'
	/opt/chefdk/bin/berks:308:in `load'
	/opt/chefdk/bin/berks:308:in `<main>'
$ berks --version
7.0.8
$

**Comment by madwort** [comment]
Hi @kahamed , I think that is a different issue as you are specifying `-c ./.berkshelf/bps_config.json`, my original issue was about which config file berkshelf opens by default.

**Comment by madwort** [comment]
(@kahamed unless you saying that berkshelf works correctly if you rename the file to `./.berkshelf/config.json` and run it without `-c`)
