### ISSUE TITLE
berks vendor cookbooks always results in Error:  '[ ... ]' does not match 'x.y.z' or 'x.y'

### ISSUE THREAD

**Issue by trinitronx** [berkshelf/berkshelf#1814]
This seems to be an error similar to that returned in #1796 :

### Problem

```
$ berks vendor cookbooks
An error occurred while reading the Berksfile:

  '[<Gem::Dependency type=:runtime name="chef" requirements=">= 12.0">]' does not match 'x.y.z' or 'x.y'
rake aborted!
Command failed with status (113): [berks vendor cookbooks...]
/Users/jcuzella/src/pub/cookbooks/lyraphase_workstation/Rakefile:16:in `block in <top (required)>'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/bin/bundle:22:in `load'
/Users/jcuzella/.rvm/gems/ruby-2.4.0@lyraphase_workstation/bin/bundle:22:in `<main>'
Tasks: TOP => berks
(See full trace by running task with --trace)
```

However, in my case it's coming from this line in my cookbook's `metadata.rb`:

```
chef_version     ">= 12.0" if respond_to?(:chef_version)
```

I've tried updating to latest ChefDK and using the vetted gems from [`chefdk-3.8.14-1.dmg`][1].  I've also tried specifying the exact version from this ChefDK with varying dependency specifiers such as:

- `chef_version     ">= 14.10.9" if respond_to?(:chef_version)`
- `chef_version     "14.10.9" if respond_to?(:chef_version)`
- `chef_version     "~> 14.10.9" if respond_to?(:chef_version)`
- `chef_version     "~> 14.10" if respond_to?(:chef_version)`
- `chef_version     ">= 14.10" if respond_to?(:chef_version)`

These all result in the same error with only difference being `requirements=" ... "` shows the same constraint string I specified:

```
$ berks vendor cookbooks
An error occurred while reading the Berksfile:

  '[<Gem::Dependency type=:runtime name="chef" requirements=">= 14.10.9">]' does not match 'x.y.z' or 'x.y'
rake aborted!
Command failed with status (113): [berks vendor cookbooks...]
/Users/jcuzella/src/pub/cookbooks/lyraphase_workstation/Rakefile:16:in `block in <top (required)>'
Tasks: TOP => berks
(See full trace by running task with --trace)
```

Finally, I tried removing `chef_version` entirely from `metadata.rb` yet I get the same error with empty version constraint array:

```
$ berks vendor cookbooks
An error occurred while reading the Berksfile:

  '[]' does not match 'x.y.z' or 'x.y'
```

### Conclusion / Question...

So it appears that `chef_version` is not working anymore at least with `berks vendor` and various versions of Chef.

Is there a recommended path forward?  I'm not sure what else to try here, as removing `chef_version` entirely doesn't fix it, and any valid semver dependency specifier doesn't seem to work either.

[1]: https://downloads.chef.io/chefdk#mac_os_x

**Comment by trinitronx** [comment]
#### Solution

So after pursuing some dead ends upgrading various gems, I ended up deciding to reinstall a newer ruby via `rvm install ruby-2.5.3`, then going down the rabbit hole of re-installing my cookbook's `Gemfile` gems into an `rvm gemset`, along with the dreaded `nokogiri` gem which was of course having compilation errors as usual.

I ended up running [`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`][1] to resolve some errors caused by missing headers on MacOS Mojave `10.14.3`.  Then, I still ran into errors with `libiconv` `x86_64` symbols not being recognized by `ld` linker.  I tried re-installing `libiconv` via homebrew yet this still didn't work.

Finally, I followed steps to install `nokogiri` with system libraries via: [`bundle config build.nokogiri --use-system-libraries
 && bundle install`][2]

Afterwards, I re-ran `berks vendor cookbooks` and somehow it fixed the `chef_version` error using this new gemset.  I tried doing the same test as before using ChefDK with the idea being that it shouldn't interact at all with my new `rvm` installed ruby + `nokogiri` + libraries.  Big surprise:  It now works in ChefDK after testing with:

```
$ eval "$( chef shell-init bash  )"
$ which berks
/opt/chefdk/bin/berks

$ berks vendor cookbooks
Resolving cookbook dependencies...
Fetching 'lyraphase_workstation' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Using chef_handler (2.1.0)
Using homebrew (3.0.0)
Using dmg (3.0.0)
Using lyraphase_workstation (2.1.1) from source at .
Using minitest-handler (1.5.0)
Using osx (0.1.0) from git://github.com/pivotal-sprout/osx.git (at master)
Using plist (0.9.4) from git://github.com/trinitronx/chef-plist.git (at develop/vendor/cookbooks/plist)
Using sprout-base (0.5.0) from git://github.com/pivotal-sprout/sprout-base.git (at master)
Vendoring chef_handler (2.1.0) to cookbooks/chef_handler
Vendoring dmg (3.0.0) to cookbooks/dmg
Vendoring homebrew (3.0.0) to cookbooks/homebrew
Vendoring lyraphase_workstation (2.1.1) to cookbooks/lyraphase_workstation
Vendoring minitest-handler (1.5.0) to cookbooks/minitest-handler
Vendoring osx (0.1.0) to cookbooks/osx
Vendoring plist (0.9.4) to cookbooks/plist
Vendoring sprout-base (0.5.0) to cookbooks/sprout-base
```


After all this, it seemed that it worked on all branches except one.  However, I then noticed this line was the difference:

```
depends          'dmg' unless respond_to?(:chef_version) and Chef::VersionConstraint.new(">= 10.14.0").include?(chef_version)
```

So the error was coming from Chef::VersionContraint comparison with an `Array` of `Gem::Dependency` objects.  So this was masking the problem a bit and version constraint was linked to the `chef_version` specification in `metadata.rb`.

Changing this to use `Chef::VERSION` instead works as intended and forcing this `VersionString` object into `String` ensures correct type is compared with `Chef::VersionConstraint`.

```
depends          'dmg' unless respond_to?(:chef_version) and Chef::VersionConstraint.new(">= 10.14.0").include?(Chef::VERSION.to_s)
```

The really unfortunate part is how it bubbled up and manifested as apparently broken `chef_version` constraint in `metadata.rb` based on the confusing error message.

So, I suppose this can be closed as red herring error message.   Hope this helps anyone running into similar problems with debugging this error message.

[1]: https://nokogiri.org/tutorials/installing_nokogiri.html#unable-to-find-libraries-on-macos-mojave
[2]: https://nokogiri.org/tutorials/installing_nokogiri.html#install-with-system-libraries
