### ISSUE TITLE
SSL issue when using vagrant's chef-client provisioner.

### ISSUE THREAD

**Issue by charlesjohnson** [berkshelf/berkshelf#378]
## Description

Attempts to use Vagrant with the chef-client provisioner when connecting to Hosted Chef result in an SSL validation error while uploading cookbooks.

``` text
read server certificate B: certificate verify failed (Faraday::Error::ConnectionFailed)
```

I have verified that the certificate and all other certificates in the chain are valid.

If I comment out the plugin in the vagrantfile, upload the cookbooks to the Chef server by hand, and then re-run vagrant provision, everything works as expected.
## Vagrantfile provisioner:

``` ruby
config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://api.opscode.com/organizations/myorg"
    chef.validation_key_path = "../../.chef/myorg-validator.pem"
    chef.validation_client_name = "myorg-validator"
    chef.run_list = ["recipe[resolver]", "recipe[myorg-chef-users::sysadmins]"]
    chef.environment = "vagrant-dev"
end
```
## Stack trace:

``` text
[Berkshelf] uploading cookbooks to 'https://api.opscode.com/organizations/myorg'
[Berkshelf] Using resolver (1.1.0)
[Berkshelf] Using myorg-chef-users (0.1.0) at path: '/Users/charlesjohnson/Development/myorg-new/cookbooks/myorg-chef-users'
[Berkshelf] Using users (1.3.0)
[Berkshelf] Uploading resolver (1.1.0) to: 'https://api.opscode.com/organizations/myorg'
/Users/charlesjohnson/.vagrant.d/gems/gems/net-http-persistent-2.8/lib/net/http/persistent/ssl_reuse.rb:70:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::Error::ConnectionFailed)
    from /Users/charlesjohnson/.vagrant.d/gems/gems/net-http-persistent-2.8/lib/net/http/persistent/ssl_reuse.rb:70:in `block in connect'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/net-http-persistent-2.8/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/net/http.rb:750:in `start'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:628:in `start'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:570:in `connection_for'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:926:in `request'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/faraday-0.8.5/lib/faraday/adapter/net_http_persistent.rb:17:in `perform_request'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/faraday-0.8.5/lib/faraday/adapter/net_http.rb:38:in `call'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/faraday-0.8.5/lib/faraday/response.rb:8:in `call'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/faraday-0.8.5/lib/faraday/response.rb:8:in `call'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/ridley-0.6.3/lib/ridley/middleware/chef_auth.rb:31:in `call'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/faraday-0.8.5/lib/faraday/connection.rb:245:in `run_request'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/faraday-0.8.5/lib/faraday/connection.rb:110:in `post'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/ridley-0.6.3/lib/ridley/resources/sandbox.rb:17:in `create'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/ridley-0.6.3/lib/ridley/chain_link.rb:22:in `method_missing'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/uploader.rb:56:in `upload'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/berksfile.rb:489:in `block in upload'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/berksfile.rb:487:in `each'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/berksfile.rb:487:in `upload'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/vagrant/action/upload.rb:28:in `block in upload'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/vagrant/action/upload.rb:26:in `each'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/vagrant/action/upload.rb:26:in `upload'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/vagrant/action/upload.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/vagrant/action/set_ui.rb:12:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/builder.rb:92:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:83:in `block in finalize_action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:84:in `block in finalize_action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/general/validate.rb:13:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/charlesjohnson/.vagrant.d/gems/gems/berkshelf-1.1.6/lib/berkshelf/vagrant/action/validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/builder.rb:92:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/runner.rb:49:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/runner.rb:49:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/vm.rb:192:in `run_action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/vm.rb:164:in `provision'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/provision.rb:24:in `block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/base.rb:116:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/base.rb:111:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/base.rb:111:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/provision.rb:19:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/cli.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/environment.rb:167:in `cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.6/bin/vagrant:43:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

**Comment by voltecrus** [comment]
@fearoffish Thank you! It worked for me.

**Comment by dupuy** [comment]
@fearoffish I was getting a bit despondent with the out-of-date suggestions (e.g. `brew install curl-ca-bundle` which no longer exists) - `export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem` did the trick for me as well, and not only fixed Berkshelf for me, but also test-kitchen.

Thanks!

**Comment by afiune** [comment]
if you are using `chefdk` the solution is to add the cert (supermarket or berks api) to the file `/opt/chefdk/embedded/ssl/certs/cacert.pem` 

Good luck guys! :smile:

**Comment by darkweasel77** [comment]
@afiune - when you say "add the cert... to the file" what cert is supposed to be added, and what would it look like? - editing cacert.pem manually and adding a reference to some thing.. etc.

Asking because it is non-obvious to me what to do.
