### ISSUE TITLE
berks upload --ssl-verify=false does not work

### ISSUE THREAD

**Issue by josephholsten** [berkshelf/berkshelf#758]
Usage docs assert an `--ssl-verify` flag exists:

```
$ bundle exec berks upload --help
Usage:
  berks upload [COOKBOOKS]

Options:
  -b, [--berksfile=PATH]        # Path to a Berksfile to operate off of.
                                # Default: /var/lib/jenkins/jenkins-data/jobs/chef/workspace/Berksfile
  -e, [--except=one two three]  # Exclude cookbooks that are in these groups.
  -o, [--only=one two three]    # Only cookbooks that are in these groups.
      [--no-freeze]             # Do not freeze uploaded cookbook(s).
      [--force]                 # Upload all cookbook(s) even if a frozen one exists on the Chef Server.
      [--ssl-verify]            # Disable/Enable SSL verification when uploading cookbooks.
  -s, [--skip-syntax-check]     # Skip Ruby syntax check when uploading cookbooks.
  -D, [--skip-dependencies]     # Skip uploading dependent cookbook(s).
      [--halt-on-frozen]        # Halt uploading and exit if the Chef Server has a frozen version of the cookbook(s).
  -c, [--config=PATH]           # Path to Berkshelf configuration to use.
  -F, [--format=FORMAT]         # Output format to use.
                                # Default: human
  -q, [--quiet]                 # Silence all informational output.
  -d, [--debug]                 # Output debug information

Upload the cookbook specified in the Berksfile to the Chef Server
```

It does not seem to turn on that function:

```
$ bundle exec berks upload --ssl-verify=false
Using ack (1.0.0)
...
Uploading ack (1.0.0) to: 'https://chef.test....net:443/'
E, [2013-07-16T23:38:23.421890 #5190] ERROR -- : Ridley::Errors::ConnectionFailed: SSL_connect returned=1 errno=0 state=SSL0v3 read server certificate B: certificate verify failed
E, [2013-07-16T23:38:23.422238 #5190] ERROR -- : /var/lib/jenkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/celluloid-0.14.1/lib/celluloid/responses.rb:29:in `value'
/var/lib/jenkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
...
/var/lib/jenkins/.rbenv/versions/1.9.3-p429/bin/berks:23:in `<main>'
There was an error connecting to the Chef Server
```

Specifying the flag in config does work:

```
$ echo '{"ssl":{"verify": false }}' > ~/.berkshelf/config.json
$ bundle exec berks upload && echo Success
Using ack (1.0.0)
...
Uploading ack (1.0.0) to: 'https://chef.test.intsm.net:443/'
...
Success
```

**Comment by giladsh1** [comment]
echo '{"ssl": { "verify": false }}' > ~/.berkshelf/config.json worked for me.  
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.14.2
