### ISSUE TITLE
Get timeout when uploading a largish cookbook

### ISSUE THREAD

**Issue by tomdz** [berkshelf/berkshelf#761]
When uploading a largish cookbook (about 300K total size), I get this when trying to upload it with berkshelf:

```
Ridley::SandboxUploader crashed!
Errno::ETIMEDOUT: Operation timed out - connect(2)
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `initialize'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `open'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `connect'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:744:in `start'
    /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1284:in `request'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:75:in `perform_request'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:38:in `call'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/middleware/chef_auth.rb:74:in `call'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/middleware/follow_redirects.rb:67:in `perform_with_redirection'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/middleware/follow_redirects.rb:60:in `call'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/response.rb:8:in `call'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in `run_request'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/connection.rb:112:in `put'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/sandbox_uploader.rb:91:in `upload'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
    /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
/Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `initialize': Operation timed out - connect(2) (Errno::ETIMEDOUT)
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `open'
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:762:in `connect'
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:744:in `start'
    from /Users/tomdz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1284:in `request'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:75:in `perform_request'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:38:in `call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/middleware/chef_auth.rb:74:in `call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/middleware/follow_redirects.rb:67:in `perform_with_redirection'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/middleware/follow_redirects.rb:60:in `call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/response.rb:8:in `call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in `run_request'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.7/lib/faraday/connection.rb:112:in `put'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/sandbox_uploader.rb:91:in `upload'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/proxies/actor_proxy.rb:25:in `_send_'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/pool_manager.rb:41:in `_send_'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/pool_manager.rb:122:in `method_missing'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/future.rb:105:in `value'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/future.rb:69:in `value'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/resources/sandbox_resource.rb:71:in `map'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/resources/sandbox_resource.rb:71:in `upload'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/chef_objects/sandbox_object.rb:46:in `upload'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/ridley-1.2.2/lib/ridley/resources/cookbook_resource.rb:205:in `upload'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/berkshelf-2.0.7/lib/berkshelf/berksfile.rb:525:in `block in upload'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/berkshelf-2.0.7/lib/berkshelf/berksfile.rb:520:in `each'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/berkshelf-2.0.7/lib/berkshelf/berksfile.rb:520:in `upload'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/berkshelf-2.0.7/lib/berkshelf/cli.rb:229:in `upload'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/berkshelf-2.0.7/lib/berkshelf/cli.rb:21:in `dispatch'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/gems/berkshelf-2.0.7/bin/berks:6:in `<top (required)>'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/bin/berks:19:in `load'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/bin/berks:19:in `<main>'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/tomdz/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

Used software versions:
- Ruby 1.9.3-p392
- Berkshelf 2.0.7
- Chef gem 11.4.2
- Chef server 11.0.8

Maybe there is a way to increase the timeout via configuration ?

**Comment by wenchma** [comment]
@ivey I also got this error when running rspec.
E, [2015-03-23T15:22:31.485407 #9764] ERROR -- : Actor crashed!
Errno::ETIMEDOUT: Connection timed out - connect(2)
	/usr/lib/ruby/1.9.1/net/http.rb:762:in `initialize'
	/usr/lib/ruby/1.9.1/net/http.rb:762:in `open'
	/usr/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
	/usr/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
	/usr/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
	/usr/lib/ruby/1.9.1/net/http.rb:762:in `connect'
	/usr/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
	/usr/lib/ruby/1.9.1/net/http.rb:744:in `start'
	/usr/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
	/usr/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
	/usr/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
	/usr/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
	/usr/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
	/usr/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
	/usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
	/usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
	/var/lib/gems/1.9.1/gems/berkshelf-3.2.3/lib/berkshelf/community_rest.rb:186:in `block in stream'
	/var/lib/gems/1.9.1/gems/retryable-2.0.1/lib/retryable.rb:63:in `retryable'
.......
