### ISSUE TITLE
3.0.0beta2: chef_config processing fails if there are knife option assignments in knife.rb

### ISSUE THREAD

**Issue by rberger** [berkshelf/berkshelf#807]
My knife.rb has lines like:

```
knife[:kvm_host] = "foo.example.com"
```

and this causes the following exception:

```
berks --version
/Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/buff-config-0.3.0/lib/buff/config/ruby.rb:23:in `rescue in initialize': undefined local variable or method `knife' for #<Buff::Config::Ruby::Evaluator:0x007fcb25890c68> (Buff::Errors::InvalidConfig)
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/buff-config-0.3.0/lib/buff/config/ruby.rb:20:in `initialize'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/buff-config-0.3.0/lib/buff/config/ruby.rb:14:in `new'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/buff-config-0.3.0/lib/buff/config/ruby.rb:14:in `parse'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/buff-config-0.3.0/lib/buff/config/ruby.rb:103:in `from_ruby'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/buff-config-0.3.0/lib/buff/config/ruby.rb:96:in `initialize'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/ridley-1.4.1/lib/ridley/chef/config.rb:83:in `initialize'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf.rb:72:in `new'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf.rb:72:in `chef_config'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/config.rb:68:in `<class:Config>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/config.rb:4:in `<module:Berkshelf>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/config.rb:3:in `<top (required)>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/cookbook_generator.rb:3:in `require_relative'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/cookbook_generator.rb:3:in `<class:CookbookGenerator>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/cookbook_generator.rb:2:in `<module:Berkshelf>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/cookbook_generator.rb:1:in `<top (required)>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf.rb:149:in `require_relative'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf.rb:149:in `<top (required)>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/cli.rb:1:in `require'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/lib/berkshelf/cli.rb:1:in `<top (required)>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/bin/berks:3:in `require'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/gems/berkshelf-3.0.0.beta2/bin/berks:3:in `<top (required)>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/bin/berks:23:in `load'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p429/bin/berks:23:in `<main>'
```

**Comment by ianrossi** [comment]
@reset I seem to be experiencing something similar. Thought I would ping here before creating an issue.

I got the following error:
```
-----> Starting Kitchen (v1.4.2)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:30:in `rescue in initialize': undefined method `[]=' for nil:NilClass (Buff::Errors::InvalidConfig)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:25:in `initialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:17:in `new'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:17:in `parse'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:119:in `from_ruby'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:112:in `initialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/chef/config.rb:83:in `initialize'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:90:in `new'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:90:in `chef_config'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:80:in `<class:Config>'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:4:in `<module:Berkshelf>'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:3:in `<top (required)>'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:2:in `require_relative'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:2:in `<top (required)>'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:195:in `require_relative'
        from /Users/a569976/.chefdk/gem/ruby/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:195:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/berkshelf.rb:95:in `load_berkshelf!'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/berkshelf.rb:54:in `load!'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_base.rb:298:in `load_needed_dependencies!'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/configurable.rb:56:in `finalize_config!'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:314:in `setup_provisioner'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:107:in `initialize'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:238:in `new'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:238:in `new_instance'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:135:in `block in build_instances'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:134:in `map'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:134:in `with_index'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:134:in `build_instances'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:110:in `instances'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:115:in `filtered_instances'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:145:in `parse_subcommand'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command/action.rb:38:in `block in call'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command/action.rb:37:in `call'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:56:in `perform'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:171:in `block (2 levels) in <class:CLI>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:308:in `invoke_task'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/chefdk/embedded/apps/test-kitchen/bin/kitchen:13:in `block in <top (required)>'
        from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/errors.rb:154:in `with_friendly_errors'
        from /opt/chefdk/embedded/apps/test-kitchen/bin/kitchen:13:in `<top (required)>'
        from /opt/chefdk/bin/kitchen:15:in `load'
        from /opt/chefdk/bin/kitchen:15:in `<main>'
```

When doing a kitchen converge on all of my cookbook repos. I removed the following lines from my knife.rb:

```
knife[:cloudformation][:credentials] = {
  :provider => :open_stack,
  :open_stack_username => ENV['OS_USERNAME'],
  :open_stack_password => ENV['OS_PASSWORD'],
  :open_stack_identity_url => ENV['OS_AUTH_URL'],
  :open_stack_tenant_name => ENV['OS_TENANT_NAME']
}
```
And it resolved the error. I was getting this with the following gem versions:
```
  * test-kitchen (1.4.2)
  * berkshelf (3.3.0)
```

**Comment by e100** [comment]
I am seeing the same issue with same versions

**Comment by DI-DaveGoodine** [comment]
I am also seeing this issue with berkshelf 3.3.0.  After I renamed by knife_override.rb, berks --version works again.
